// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct _complex {
 *     double x;
 *     double y;
 * };
 * }
 */
public class _complex {

    public static MemoryLayout $LAYOUT() {
        return constants$14.const$3;
    }
    public static VarHandle x$VH() {
        return constants$14.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * double x;
     * }
     */
    public static double x$get(MemorySegment seg) {
        return (double)constants$14.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * double x;
     * }
     */
    public static void x$set(MemorySegment seg, double x) {
        constants$14.const$4.set(seg, x);
    }
    public static double x$get(MemorySegment seg, long index) {
        return (double)constants$14.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, double x) {
        constants$14.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle y$VH() {
        return constants$14.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * double y;
     * }
     */
    public static double y$get(MemorySegment seg) {
        return (double)constants$14.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * double y;
     * }
     */
    public static void y$set(MemorySegment seg, double x) {
        constants$14.const$5.set(seg, x);
    }
    public static double y$get(MemorySegment seg, long index) {
        return (double)constants$14.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, double x) {
        constants$14.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


