// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * union _float_const {
 *     unsigned short _Word[4];
 *     float _Float;
 *     double _Double;
 *     long double _Long_double;
 * };
 * }
 */
public class _float_const {

    public static MemoryLayout $LAYOUT() {
        return constants$24.const$0;
    }
    public static MemorySegment _Word$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static VarHandle _Float$VH() {
        return constants$24.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float _Float;
     * }
     */
    public static float _Float$get(MemorySegment seg) {
        return (float)constants$24.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float _Float;
     * }
     */
    public static void _Float$set(MemorySegment seg, float x) {
        constants$24.const$1.set(seg, x);
    }
    public static float _Float$get(MemorySegment seg, long index) {
        return (float)constants$24.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void _Float$set(MemorySegment seg, long index, float x) {
        constants$24.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle _Double$VH() {
        return constants$24.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * double _Double;
     * }
     */
    public static double _Double$get(MemorySegment seg) {
        return (double)constants$24.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * double _Double;
     * }
     */
    public static void _Double$set(MemorySegment seg, double x) {
        constants$24.const$2.set(seg, x);
    }
    public static double _Double$get(MemorySegment seg, long index) {
        return (double)constants$24.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void _Double$set(MemorySegment seg, long index, double x) {
        constants$24.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle _Long_double$VH() {
        return constants$24.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * long double _Long_double;
     * }
     */
    public static double _Long_double$get(MemorySegment seg) {
        return (double)constants$24.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * long double _Long_double;
     * }
     */
    public static void _Long_double$set(MemorySegment seg, double x) {
        constants$24.const$3.set(seg, x);
    }
    public static double _Long_double$get(MemorySegment seg, long index) {
        return (double)constants$24.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void _Long_double$set(MemorySegment seg, long index, double x) {
        constants$24.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


