// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * int (*b2AssertFcn)(char* condition,char* fileName,int lineNumber);
 * }
 */
public interface b2AssertFcn {

    int apply(java.lang.foreign.MemorySegment condition, java.lang.foreign.MemorySegment fileName, int lineNumber);
    static MemorySegment allocate(b2AssertFcn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2.const$3, fi, constants$2.const$2, scope);
    }
    static b2AssertFcn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _condition, java.lang.foreign.MemorySegment _fileName, int _lineNumber) -> {
            try {
                return (int)constants$2.const$4.invokeExact(symbol, _condition, _fileName, _lineNumber);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


