// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2BodyEvents {
 *     struct b2BodyMoveEvent* moveEvents;
 *     int moveCount;
 * };
 * }
 */
public class b2BodyEvents {

    public static MemoryLayout $LAYOUT() {
        return constants$146.const$3;
    }
    public static VarHandle moveEvents$VH() {
        return constants$146.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2BodyMoveEvent* moveEvents;
     * }
     */
    public static MemorySegment moveEvents$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$146.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2BodyMoveEvent* moveEvents;
     * }
     */
    public static void moveEvents$set(MemorySegment seg, MemorySegment x) {
        constants$146.const$4.set(seg, x);
    }
    public static MemorySegment moveEvents$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$146.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void moveEvents$set(MemorySegment seg, long index, MemorySegment x) {
        constants$146.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle moveCount$VH() {
        return constants$146.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int moveCount;
     * }
     */
    public static int moveCount$get(MemorySegment seg) {
        return (int)constants$146.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int moveCount;
     * }
     */
    public static void moveCount$set(MemorySegment seg, int x) {
        constants$146.const$5.set(seg, x);
    }
    public static int moveCount$get(MemorySegment seg, long index) {
        return (int)constants$146.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void moveCount$set(MemorySegment seg, long index, int x) {
        constants$146.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


