// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * float (*b2CastResultFcn)(struct b2ShapeId shapeId,struct b2Vec2 point,struct b2Vec2 normal,float fraction,void* context);
 * }
 */
public interface b2CastResultFcn {

    float apply(java.lang.foreign.MemorySegment shapeId, java.lang.foreign.MemorySegment point, java.lang.foreign.MemorySegment normal, float fraction, java.lang.foreign.MemorySegment context);
    static MemorySegment allocate(b2CastResultFcn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$148.const$5, fi, constants$148.const$4, scope);
    }
    static b2CastResultFcn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _shapeId, java.lang.foreign.MemorySegment _point, java.lang.foreign.MemorySegment _normal, float _fraction, java.lang.foreign.MemorySegment _context) -> {
            try {
                return (float)constants$149.const$0.invokeExact(symbol, _shapeId, _point, _normal, _fraction, _context);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


