// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2ChainId {
 *     int index1;
 *     unsigned short world0;
 *     unsigned short generation;
 * };
 * }
 */
public class b2ChainId {

    public static MemoryLayout $LAYOUT() {
        return constants$101.const$1;
    }
    public static VarHandle index1$VH() {
        return constants$101.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int index1;
     * }
     */
    public static int index1$get(MemorySegment seg) {
        return (int)constants$101.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int index1;
     * }
     */
    public static void index1$set(MemorySegment seg, int x) {
        constants$101.const$2.set(seg, x);
    }
    public static int index1$get(MemorySegment seg, long index) {
        return (int)constants$101.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void index1$set(MemorySegment seg, long index, int x) {
        constants$101.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle world0$VH() {
        return constants$101.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short world0;
     * }
     */
    public static short world0$get(MemorySegment seg) {
        return (short)constants$101.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short world0;
     * }
     */
    public static void world0$set(MemorySegment seg, short x) {
        constants$101.const$3.set(seg, x);
    }
    public static short world0$get(MemorySegment seg, long index) {
        return (short)constants$101.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void world0$set(MemorySegment seg, long index, short x) {
        constants$101.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle generation$VH() {
        return constants$101.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short generation;
     * }
     */
    public static short generation$get(MemorySegment seg) {
        return (short)constants$101.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short generation;
     * }
     */
    public static void generation$set(MemorySegment seg, short x) {
        constants$101.const$4.set(seg, x);
    }
    public static short generation$get(MemorySegment seg, long index) {
        return (short)constants$101.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void generation$set(MemorySegment seg, long index, short x) {
        constants$101.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


