// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Counters {
 *     int bodyCount;
 *     int shapeCount;
 *     int contactCount;
 *     int jointCount;
 *     int islandCount;
 *     int stackUsed;
 *     int staticTreeHeight;
 *     int treeHeight;
 *     int byteCount;
 *     int taskCount;
 *     int colorCounts[12];
 * };
 * }
 */
public class b2Counters {

    public static MemoryLayout $LAYOUT() {
        return constants$123.const$1;
    }
    public static VarHandle bodyCount$VH() {
        return constants$123.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bodyCount;
     * }
     */
    public static int bodyCount$get(MemorySegment seg) {
        return (int)constants$123.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bodyCount;
     * }
     */
    public static void bodyCount$set(MemorySegment seg, int x) {
        constants$123.const$2.set(seg, x);
    }
    public static int bodyCount$get(MemorySegment seg, long index) {
        return (int)constants$123.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void bodyCount$set(MemorySegment seg, long index, int x) {
        constants$123.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle shapeCount$VH() {
        return constants$123.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int shapeCount;
     * }
     */
    public static int shapeCount$get(MemorySegment seg) {
        return (int)constants$123.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int shapeCount;
     * }
     */
    public static void shapeCount$set(MemorySegment seg, int x) {
        constants$123.const$3.set(seg, x);
    }
    public static int shapeCount$get(MemorySegment seg, long index) {
        return (int)constants$123.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void shapeCount$set(MemorySegment seg, long index, int x) {
        constants$123.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle contactCount$VH() {
        return constants$123.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int contactCount;
     * }
     */
    public static int contactCount$get(MemorySegment seg) {
        return (int)constants$123.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int contactCount;
     * }
     */
    public static void contactCount$set(MemorySegment seg, int x) {
        constants$123.const$4.set(seg, x);
    }
    public static int contactCount$get(MemorySegment seg, long index) {
        return (int)constants$123.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void contactCount$set(MemorySegment seg, long index, int x) {
        constants$123.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle jointCount$VH() {
        return constants$123.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int jointCount;
     * }
     */
    public static int jointCount$get(MemorySegment seg) {
        return (int)constants$123.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int jointCount;
     * }
     */
    public static void jointCount$set(MemorySegment seg, int x) {
        constants$123.const$5.set(seg, x);
    }
    public static int jointCount$get(MemorySegment seg, long index) {
        return (int)constants$123.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void jointCount$set(MemorySegment seg, long index, int x) {
        constants$123.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle islandCount$VH() {
        return constants$124.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int islandCount;
     * }
     */
    public static int islandCount$get(MemorySegment seg) {
        return (int)constants$124.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int islandCount;
     * }
     */
    public static void islandCount$set(MemorySegment seg, int x) {
        constants$124.const$0.set(seg, x);
    }
    public static int islandCount$get(MemorySegment seg, long index) {
        return (int)constants$124.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void islandCount$set(MemorySegment seg, long index, int x) {
        constants$124.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle stackUsed$VH() {
        return constants$124.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stackUsed;
     * }
     */
    public static int stackUsed$get(MemorySegment seg) {
        return (int)constants$124.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stackUsed;
     * }
     */
    public static void stackUsed$set(MemorySegment seg, int x) {
        constants$124.const$1.set(seg, x);
    }
    public static int stackUsed$get(MemorySegment seg, long index) {
        return (int)constants$124.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void stackUsed$set(MemorySegment seg, long index, int x) {
        constants$124.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle staticTreeHeight$VH() {
        return constants$124.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int staticTreeHeight;
     * }
     */
    public static int staticTreeHeight$get(MemorySegment seg) {
        return (int)constants$124.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int staticTreeHeight;
     * }
     */
    public static void staticTreeHeight$set(MemorySegment seg, int x) {
        constants$124.const$2.set(seg, x);
    }
    public static int staticTreeHeight$get(MemorySegment seg, long index) {
        return (int)constants$124.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void staticTreeHeight$set(MemorySegment seg, long index, int x) {
        constants$124.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle treeHeight$VH() {
        return constants$124.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int treeHeight;
     * }
     */
    public static int treeHeight$get(MemorySegment seg) {
        return (int)constants$124.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int treeHeight;
     * }
     */
    public static void treeHeight$set(MemorySegment seg, int x) {
        constants$124.const$3.set(seg, x);
    }
    public static int treeHeight$get(MemorySegment seg, long index) {
        return (int)constants$124.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void treeHeight$set(MemorySegment seg, long index, int x) {
        constants$124.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle byteCount$VH() {
        return constants$124.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int byteCount;
     * }
     */
    public static int byteCount$get(MemorySegment seg) {
        return (int)constants$124.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int byteCount;
     * }
     */
    public static void byteCount$set(MemorySegment seg, int x) {
        constants$124.const$4.set(seg, x);
    }
    public static int byteCount$get(MemorySegment seg, long index) {
        return (int)constants$124.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void byteCount$set(MemorySegment seg, long index, int x) {
        constants$124.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle taskCount$VH() {
        return constants$124.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int taskCount;
     * }
     */
    public static int taskCount$get(MemorySegment seg) {
        return (int)constants$124.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int taskCount;
     * }
     */
    public static void taskCount$set(MemorySegment seg, int x) {
        constants$124.const$5.set(seg, x);
    }
    public static int taskCount$get(MemorySegment seg, long index) {
        return (int)constants$124.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void taskCount$set(MemorySegment seg, long index, int x) {
        constants$124.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment colorCounts$slice(MemorySegment seg) {
        return seg.asSlice(40, 48);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


