// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2ContactEvents {
 *     struct b2ContactBeginTouchEvent* beginEvents;
 *     struct b2ContactEndTouchEvent* endEvents;
 *     struct b2ContactHitEvent* hitEvents;
 *     int beginCount;
 *     int endCount;
 *     int hitCount;
 * };
 * }
 */
public class b2ContactEvents {

    public static MemoryLayout $LAYOUT() {
        return constants$144.const$5;
    }
    public static VarHandle beginEvents$VH() {
        return constants$145.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2ContactBeginTouchEvent* beginEvents;
     * }
     */
    public static MemorySegment beginEvents$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$145.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2ContactBeginTouchEvent* beginEvents;
     * }
     */
    public static void beginEvents$set(MemorySegment seg, MemorySegment x) {
        constants$145.const$0.set(seg, x);
    }
    public static MemorySegment beginEvents$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$145.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void beginEvents$set(MemorySegment seg, long index, MemorySegment x) {
        constants$145.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle endEvents$VH() {
        return constants$145.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2ContactEndTouchEvent* endEvents;
     * }
     */
    public static MemorySegment endEvents$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$145.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2ContactEndTouchEvent* endEvents;
     * }
     */
    public static void endEvents$set(MemorySegment seg, MemorySegment x) {
        constants$145.const$1.set(seg, x);
    }
    public static MemorySegment endEvents$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$145.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void endEvents$set(MemorySegment seg, long index, MemorySegment x) {
        constants$145.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hitEvents$VH() {
        return constants$145.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2ContactHitEvent* hitEvents;
     * }
     */
    public static MemorySegment hitEvents$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$145.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2ContactHitEvent* hitEvents;
     * }
     */
    public static void hitEvents$set(MemorySegment seg, MemorySegment x) {
        constants$145.const$2.set(seg, x);
    }
    public static MemorySegment hitEvents$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$145.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void hitEvents$set(MemorySegment seg, long index, MemorySegment x) {
        constants$145.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle beginCount$VH() {
        return constants$145.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int beginCount;
     * }
     */
    public static int beginCount$get(MemorySegment seg) {
        return (int)constants$145.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int beginCount;
     * }
     */
    public static void beginCount$set(MemorySegment seg, int x) {
        constants$145.const$3.set(seg, x);
    }
    public static int beginCount$get(MemorySegment seg, long index) {
        return (int)constants$145.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void beginCount$set(MemorySegment seg, long index, int x) {
        constants$145.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle endCount$VH() {
        return constants$145.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int endCount;
     * }
     */
    public static int endCount$get(MemorySegment seg) {
        return (int)constants$145.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int endCount;
     * }
     */
    public static void endCount$set(MemorySegment seg, int x) {
        constants$145.const$4.set(seg, x);
    }
    public static int endCount$get(MemorySegment seg, long index) {
        return (int)constants$145.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void endCount$set(MemorySegment seg, long index, int x) {
        constants$145.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hitCount$VH() {
        return constants$145.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int hitCount;
     * }
     */
    public static int hitCount$get(MemorySegment seg) {
        return (int)constants$145.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int hitCount;
     * }
     */
    public static void hitCount$set(MemorySegment seg, int x) {
        constants$145.const$5.set(seg, x);
    }
    public static int hitCount$get(MemorySegment seg, long index) {
        return (int)constants$145.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void hitCount$set(MemorySegment seg, long index, int x) {
        constants$145.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


