// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2ContactHitEvent {
 *     struct b2ShapeId shapeIdA;
 *     struct b2ShapeId shapeIdB;
 *     struct b2Vec2 point;
 *     struct b2Vec2 normal;
 *     float approachSpeed;
 * };
 * }
 */
public class b2ContactHitEvent {

    public static MemoryLayout $LAYOUT() {
        return constants$144.const$3;
    }
    public static MemorySegment shapeIdA$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment shapeIdB$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static MemorySegment point$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment normal$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static VarHandle approachSpeed$VH() {
        return constants$144.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float approachSpeed;
     * }
     */
    public static float approachSpeed$get(MemorySegment seg) {
        return (float)constants$144.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float approachSpeed;
     * }
     */
    public static void approachSpeed$set(MemorySegment seg, float x) {
        constants$144.const$4.set(seg, x);
    }
    public static float approachSpeed$get(MemorySegment seg, long index) {
        return (float)constants$144.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void approachSpeed$set(MemorySegment seg, long index, float x) {
        constants$144.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


