// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2DistanceInput {
 *     struct b2ShapeProxy proxyA;
 *     struct b2ShapeProxy proxyB;
 *     struct b2Transform transformA;
 *     struct b2Transform transformB;
 *     _Bool useRadii;
 * };
 * }
 */
public class b2DistanceInput {

    public static MemoryLayout $LAYOUT() {
        return constants$79.const$0;
    }
    public static MemorySegment proxyA$slice(MemorySegment seg) {
        return seg.asSlice(0, 72);
    }
    public static MemorySegment proxyB$slice(MemorySegment seg) {
        return seg.asSlice(72, 72);
    }
    public static MemorySegment transformA$slice(MemorySegment seg) {
        return seg.asSlice(144, 16);
    }
    public static MemorySegment transformB$slice(MemorySegment seg) {
        return seg.asSlice(160, 16);
    }
    public static VarHandle useRadii$VH() {
        return constants$79.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool useRadii;
     * }
     */
    public static boolean useRadii$get(MemorySegment seg) {
        return (boolean)constants$79.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool useRadii;
     * }
     */
    public static void useRadii$set(MemorySegment seg, boolean x) {
        constants$79.const$1.set(seg, x);
    }
    public static boolean useRadii$get(MemorySegment seg, long index) {
        return (boolean)constants$79.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void useRadii$set(MemorySegment seg, long index, boolean x) {
        constants$79.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


