// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2DynamicTree {
 *     struct b2TreeNode* nodes;
 *     int root;
 *     int nodeCount;
 *     int nodeCapacity;
 *     int freeList;
 *     int proxyCount;
 *     int* leafIndices;
 *     struct b2AABB* leafBoxes;
 *     struct b2Vec2* leafCenters;
 *     int* binIndices;
 *     int rebuildCapacity;
 * };
 * }
 */
public class b2DynamicTree {

    public static MemoryLayout $LAYOUT() {
        return constants$88.const$0;
    }
    public static VarHandle nodes$VH() {
        return constants$88.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2TreeNode* nodes;
     * }
     */
    public static MemorySegment nodes$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$88.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2TreeNode* nodes;
     * }
     */
    public static void nodes$set(MemorySegment seg, MemorySegment x) {
        constants$88.const$1.set(seg, x);
    }
    public static MemorySegment nodes$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$88.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void nodes$set(MemorySegment seg, long index, MemorySegment x) {
        constants$88.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle root$VH() {
        return constants$88.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int root;
     * }
     */
    public static int root$get(MemorySegment seg) {
        return (int)constants$88.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int root;
     * }
     */
    public static void root$set(MemorySegment seg, int x) {
        constants$88.const$2.set(seg, x);
    }
    public static int root$get(MemorySegment seg, long index) {
        return (int)constants$88.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void root$set(MemorySegment seg, long index, int x) {
        constants$88.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle nodeCount$VH() {
        return constants$88.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nodeCount;
     * }
     */
    public static int nodeCount$get(MemorySegment seg) {
        return (int)constants$88.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nodeCount;
     * }
     */
    public static void nodeCount$set(MemorySegment seg, int x) {
        constants$88.const$3.set(seg, x);
    }
    public static int nodeCount$get(MemorySegment seg, long index) {
        return (int)constants$88.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void nodeCount$set(MemorySegment seg, long index, int x) {
        constants$88.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle nodeCapacity$VH() {
        return constants$88.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nodeCapacity;
     * }
     */
    public static int nodeCapacity$get(MemorySegment seg) {
        return (int)constants$88.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nodeCapacity;
     * }
     */
    public static void nodeCapacity$set(MemorySegment seg, int x) {
        constants$88.const$4.set(seg, x);
    }
    public static int nodeCapacity$get(MemorySegment seg, long index) {
        return (int)constants$88.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void nodeCapacity$set(MemorySegment seg, long index, int x) {
        constants$88.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle freeList$VH() {
        return constants$88.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int freeList;
     * }
     */
    public static int freeList$get(MemorySegment seg) {
        return (int)constants$88.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int freeList;
     * }
     */
    public static void freeList$set(MemorySegment seg, int x) {
        constants$88.const$5.set(seg, x);
    }
    public static int freeList$get(MemorySegment seg, long index) {
        return (int)constants$88.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void freeList$set(MemorySegment seg, long index, int x) {
        constants$88.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle proxyCount$VH() {
        return constants$89.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int proxyCount;
     * }
     */
    public static int proxyCount$get(MemorySegment seg) {
        return (int)constants$89.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int proxyCount;
     * }
     */
    public static void proxyCount$set(MemorySegment seg, int x) {
        constants$89.const$0.set(seg, x);
    }
    public static int proxyCount$get(MemorySegment seg, long index) {
        return (int)constants$89.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void proxyCount$set(MemorySegment seg, long index, int x) {
        constants$89.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle leafIndices$VH() {
        return constants$89.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int* leafIndices;
     * }
     */
    public static MemorySegment leafIndices$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$89.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int* leafIndices;
     * }
     */
    public static void leafIndices$set(MemorySegment seg, MemorySegment x) {
        constants$89.const$1.set(seg, x);
    }
    public static MemorySegment leafIndices$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$89.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void leafIndices$set(MemorySegment seg, long index, MemorySegment x) {
        constants$89.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle leafBoxes$VH() {
        return constants$89.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2AABB* leafBoxes;
     * }
     */
    public static MemorySegment leafBoxes$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$89.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2AABB* leafBoxes;
     * }
     */
    public static void leafBoxes$set(MemorySegment seg, MemorySegment x) {
        constants$89.const$2.set(seg, x);
    }
    public static MemorySegment leafBoxes$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$89.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void leafBoxes$set(MemorySegment seg, long index, MemorySegment x) {
        constants$89.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle leafCenters$VH() {
        return constants$89.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct b2Vec2* leafCenters;
     * }
     */
    public static MemorySegment leafCenters$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$89.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct b2Vec2* leafCenters;
     * }
     */
    public static void leafCenters$set(MemorySegment seg, MemorySegment x) {
        constants$89.const$3.set(seg, x);
    }
    public static MemorySegment leafCenters$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$89.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void leafCenters$set(MemorySegment seg, long index, MemorySegment x) {
        constants$89.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle binIndices$VH() {
        return constants$89.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int* binIndices;
     * }
     */
    public static MemorySegment binIndices$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$89.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int* binIndices;
     * }
     */
    public static void binIndices$set(MemorySegment seg, MemorySegment x) {
        constants$89.const$4.set(seg, x);
    }
    public static MemorySegment binIndices$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$89.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void binIndices$set(MemorySegment seg, long index, MemorySegment x) {
        constants$89.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle rebuildCapacity$VH() {
        return constants$89.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int rebuildCapacity;
     * }
     */
    public static int rebuildCapacity$get(MemorySegment seg) {
        return (int)constants$89.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int rebuildCapacity;
     * }
     */
    public static void rebuildCapacity$set(MemorySegment seg, int x) {
        constants$89.const$5.set(seg, x);
    }
    public static int rebuildCapacity$get(MemorySegment seg, long index) {
        return (int)constants$89.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void rebuildCapacity$set(MemorySegment seg, long index, int x) {
        constants$89.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


