// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * float (*b2DynamicTree_RayCast$callback)(struct b2RayCastInput*,int,unsigned long long,void*);
 * }
 */
public interface b2DynamicTree_RayCast$callback {

    float apply(java.lang.foreign.MemorySegment input, int proxyId, long userData, java.lang.foreign.MemorySegment context);
    static MemorySegment allocate(b2DynamicTree_RayCast$callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$94.const$2, fi, constants$93.const$5, scope);
    }
    static b2DynamicTree_RayCast$callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _input, int _proxyId, long _userData, java.lang.foreign.MemorySegment _context) -> {
            try {
                return (float)constants$94.const$1.invokeExact(symbol, _input, _proxyId, _userData, _context);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


