// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void* (*b2EnqueueTaskCallback)(void (*task)(int,int,unsigned int,void*),int itemCount,int minRange,void* taskContext,void* userContext);
 * }
 */
public interface b2EnqueueTaskCallback {

    java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment task, int itemCount, int minRange, java.lang.foreign.MemorySegment taskContext, java.lang.foreign.MemorySegment userContext);
    static MemorySegment allocate(b2EnqueueTaskCallback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$103.const$1, fi, constants$103.const$0, scope);
    }
    static b2EnqueueTaskCallback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _task, int _itemCount, int _minRange, java.lang.foreign.MemorySegment _taskContext, java.lang.foreign.MemorySegment _userContext) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$103.const$2.invokeExact(symbol, _task, _itemCount, _minRange, _taskContext, _userContext);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


