// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void (*b2FreeFcn)(void* mem);
 * }
 */
public interface b2FreeFcn {

    void apply(java.lang.foreign.MemorySegment mem);
    static MemorySegment allocate(b2FreeFcn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2.const$0, fi, constants$0.const$0, scope);
    }
    static b2FreeFcn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _mem) -> {
            try {
                constants$2.const$1.invokeExact(symbol, _mem);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


