// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Manifold {
 *     struct b2Vec2 normal;
 *     float rollingImpulse;
 *     struct b2ManifoldPoint points[2];
 *     int pointCount;
 * };
 * }
 */
public class b2Manifold {

    public static MemoryLayout $LAYOUT() {
        return constants$85.const$2;
    }
    public static MemorySegment normal$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static VarHandle rollingImpulse$VH() {
        return constants$85.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float rollingImpulse;
     * }
     */
    public static float rollingImpulse$get(MemorySegment seg) {
        return (float)constants$85.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float rollingImpulse;
     * }
     */
    public static void rollingImpulse$set(MemorySegment seg, float x) {
        constants$85.const$3.set(seg, x);
    }
    public static float rollingImpulse$get(MemorySegment seg, long index) {
        return (float)constants$85.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void rollingImpulse$set(MemorySegment seg, long index, float x) {
        constants$85.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment points$slice(MemorySegment seg) {
        return seg.asSlice(12, 96);
    }
    public static VarHandle pointCount$VH() {
        return constants$85.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pointCount;
     * }
     */
    public static int pointCount$get(MemorySegment seg) {
        return (int)constants$85.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pointCount;
     * }
     */
    public static void pointCount$set(MemorySegment seg, int x) {
        constants$85.const$4.set(seg, x);
    }
    public static int pointCount$get(MemorySegment seg, long index) {
        return (int)constants$85.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pointCount$set(MemorySegment seg, long index, int x) {
        constants$85.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


