// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2MassData {
 *     float mass;
 *     struct b2Vec2 center;
 *     float rotationalInertia;
 * };
 * }
 */
public class b2MassData {

    public static MemoryLayout $LAYOUT() {
        return constants$68.const$0;
    }
    public static VarHandle mass$VH() {
        return constants$68.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float mass;
     * }
     */
    public static float mass$get(MemorySegment seg) {
        return (float)constants$68.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float mass;
     * }
     */
    public static void mass$set(MemorySegment seg, float x) {
        constants$68.const$1.set(seg, x);
    }
    public static float mass$get(MemorySegment seg, long index) {
        return (float)constants$68.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mass$set(MemorySegment seg, long index, float x) {
        constants$68.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment center$slice(MemorySegment seg) {
        return seg.asSlice(4, 8);
    }
    public static VarHandle rotationalInertia$VH() {
        return constants$68.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float rotationalInertia;
     * }
     */
    public static float rotationalInertia$get(MemorySegment seg) {
        return (float)constants$68.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float rotationalInertia;
     * }
     */
    public static void rotationalInertia$set(MemorySegment seg, float x) {
        constants$68.const$2.set(seg, x);
    }
    public static float rotationalInertia$get(MemorySegment seg, long index) {
        return (float)constants$68.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void rotationalInertia$set(MemorySegment seg, long index, float x) {
        constants$68.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


