// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Polygon {
 *     struct b2Vec2 vertices[8];
 *     struct b2Vec2 normals[8];
 *     struct b2Vec2 centroid;
 *     float radius;
 *     int count;
 * };
 * }
 */
public class b2Polygon {

    public static MemoryLayout $LAYOUT() {
        return constants$69.const$1;
    }
    public static MemorySegment vertices$slice(MemorySegment seg) {
        return seg.asSlice(0, 64);
    }
    public static MemorySegment normals$slice(MemorySegment seg) {
        return seg.asSlice(64, 64);
    }
    public static MemorySegment centroid$slice(MemorySegment seg) {
        return seg.asSlice(128, 8);
    }
    public static VarHandle radius$VH() {
        return constants$69.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float radius;
     * }
     */
    public static float radius$get(MemorySegment seg) {
        return (float)constants$69.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float radius;
     * }
     */
    public static void radius$set(MemorySegment seg, float x) {
        constants$69.const$2.set(seg, x);
    }
    public static float radius$get(MemorySegment seg, long index) {
        return (float)constants$69.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void radius$set(MemorySegment seg, long index, float x) {
        constants$69.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle count$VH() {
        return constants$69.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int count;
     * }
     */
    public static int count$get(MemorySegment seg) {
        return (int)constants$69.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int count;
     * }
     */
    public static void count$set(MemorySegment seg, int x) {
        constants$69.const$3.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)constants$69.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        constants$69.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


