// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2PrismaticJointDef {
 *     struct b2BodyId bodyIdA;
 *     struct b2BodyId bodyIdB;
 *     struct b2Vec2 localAnchorA;
 *     struct b2Vec2 localAnchorB;
 *     struct b2Vec2 localAxisA;
 *     float referenceAngle;
 *     float targetTranslation;
 *     _Bool enableSpring;
 *     float hertz;
 *     float dampingRatio;
 *     _Bool enableLimit;
 *     float lowerTranslation;
 *     float upperTranslation;
 *     _Bool enableMotor;
 *     float maxMotorForce;
 *     float motorSpeed;
 *     _Bool collideConnected;
 *     void* userData;
 *     int internalValue;
 * };
 * }
 */
public class b2PrismaticJointDef {

    public static MemoryLayout $LAYOUT() {
        return constants$131.const$4;
    }
    public static MemorySegment bodyIdA$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment bodyIdB$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static MemorySegment localAnchorA$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment localAnchorB$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static MemorySegment localAxisA$slice(MemorySegment seg) {
        return seg.asSlice(32, 8);
    }
    public static VarHandle referenceAngle$VH() {
        return constants$131.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float referenceAngle;
     * }
     */
    public static float referenceAngle$get(MemorySegment seg) {
        return (float)constants$131.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float referenceAngle;
     * }
     */
    public static void referenceAngle$set(MemorySegment seg, float x) {
        constants$131.const$5.set(seg, x);
    }
    public static float referenceAngle$get(MemorySegment seg, long index) {
        return (float)constants$131.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void referenceAngle$set(MemorySegment seg, long index, float x) {
        constants$131.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle targetTranslation$VH() {
        return constants$132.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float targetTranslation;
     * }
     */
    public static float targetTranslation$get(MemorySegment seg) {
        return (float)constants$132.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float targetTranslation;
     * }
     */
    public static void targetTranslation$set(MemorySegment seg, float x) {
        constants$132.const$0.set(seg, x);
    }
    public static float targetTranslation$get(MemorySegment seg, long index) {
        return (float)constants$132.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void targetTranslation$set(MemorySegment seg, long index, float x) {
        constants$132.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enableSpring$VH() {
        return constants$132.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSpring;
     * }
     */
    public static boolean enableSpring$get(MemorySegment seg) {
        return (boolean)constants$132.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSpring;
     * }
     */
    public static void enableSpring$set(MemorySegment seg, boolean x) {
        constants$132.const$1.set(seg, x);
    }
    public static boolean enableSpring$get(MemorySegment seg, long index) {
        return (boolean)constants$132.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void enableSpring$set(MemorySegment seg, long index, boolean x) {
        constants$132.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hertz$VH() {
        return constants$132.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hertz;
     * }
     */
    public static float hertz$get(MemorySegment seg) {
        return (float)constants$132.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hertz;
     * }
     */
    public static void hertz$set(MemorySegment seg, float x) {
        constants$132.const$2.set(seg, x);
    }
    public static float hertz$get(MemorySegment seg, long index) {
        return (float)constants$132.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void hertz$set(MemorySegment seg, long index, float x) {
        constants$132.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle dampingRatio$VH() {
        return constants$132.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float dampingRatio;
     * }
     */
    public static float dampingRatio$get(MemorySegment seg) {
        return (float)constants$132.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float dampingRatio;
     * }
     */
    public static void dampingRatio$set(MemorySegment seg, float x) {
        constants$132.const$3.set(seg, x);
    }
    public static float dampingRatio$get(MemorySegment seg, long index) {
        return (float)constants$132.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void dampingRatio$set(MemorySegment seg, long index, float x) {
        constants$132.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enableLimit$VH() {
        return constants$132.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableLimit;
     * }
     */
    public static boolean enableLimit$get(MemorySegment seg) {
        return (boolean)constants$132.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableLimit;
     * }
     */
    public static void enableLimit$set(MemorySegment seg, boolean x) {
        constants$132.const$4.set(seg, x);
    }
    public static boolean enableLimit$get(MemorySegment seg, long index) {
        return (boolean)constants$132.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void enableLimit$set(MemorySegment seg, long index, boolean x) {
        constants$132.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle lowerTranslation$VH() {
        return constants$132.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float lowerTranslation;
     * }
     */
    public static float lowerTranslation$get(MemorySegment seg) {
        return (float)constants$132.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float lowerTranslation;
     * }
     */
    public static void lowerTranslation$set(MemorySegment seg, float x) {
        constants$132.const$5.set(seg, x);
    }
    public static float lowerTranslation$get(MemorySegment seg, long index) {
        return (float)constants$132.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void lowerTranslation$set(MemorySegment seg, long index, float x) {
        constants$132.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle upperTranslation$VH() {
        return constants$133.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float upperTranslation;
     * }
     */
    public static float upperTranslation$get(MemorySegment seg) {
        return (float)constants$133.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float upperTranslation;
     * }
     */
    public static void upperTranslation$set(MemorySegment seg, float x) {
        constants$133.const$0.set(seg, x);
    }
    public static float upperTranslation$get(MemorySegment seg, long index) {
        return (float)constants$133.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void upperTranslation$set(MemorySegment seg, long index, float x) {
        constants$133.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enableMotor$VH() {
        return constants$133.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableMotor;
     * }
     */
    public static boolean enableMotor$get(MemorySegment seg) {
        return (boolean)constants$133.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableMotor;
     * }
     */
    public static void enableMotor$set(MemorySegment seg, boolean x) {
        constants$133.const$1.set(seg, x);
    }
    public static boolean enableMotor$get(MemorySegment seg, long index) {
        return (boolean)constants$133.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void enableMotor$set(MemorySegment seg, long index, boolean x) {
        constants$133.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxMotorForce$VH() {
        return constants$133.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxMotorForce;
     * }
     */
    public static float maxMotorForce$get(MemorySegment seg) {
        return (float)constants$133.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxMotorForce;
     * }
     */
    public static void maxMotorForce$set(MemorySegment seg, float x) {
        constants$133.const$2.set(seg, x);
    }
    public static float maxMotorForce$get(MemorySegment seg, long index) {
        return (float)constants$133.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maxMotorForce$set(MemorySegment seg, long index, float x) {
        constants$133.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle motorSpeed$VH() {
        return constants$133.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float motorSpeed;
     * }
     */
    public static float motorSpeed$get(MemorySegment seg) {
        return (float)constants$133.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float motorSpeed;
     * }
     */
    public static void motorSpeed$set(MemorySegment seg, float x) {
        constants$133.const$3.set(seg, x);
    }
    public static float motorSpeed$get(MemorySegment seg, long index) {
        return (float)constants$133.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void motorSpeed$set(MemorySegment seg, long index, float x) {
        constants$133.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle collideConnected$VH() {
        return constants$133.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool collideConnected;
     * }
     */
    public static boolean collideConnected$get(MemorySegment seg) {
        return (boolean)constants$133.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool collideConnected;
     * }
     */
    public static void collideConnected$set(MemorySegment seg, boolean x) {
        constants$133.const$4.set(seg, x);
    }
    public static boolean collideConnected$get(MemorySegment seg, long index) {
        return (boolean)constants$133.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void collideConnected$set(MemorySegment seg, long index, boolean x) {
        constants$133.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle userData$VH() {
        return constants$133.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static MemorySegment userData$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$133.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static void userData$set(MemorySegment seg, MemorySegment x) {
        constants$133.const$5.set(seg, x);
    }
    public static MemorySegment userData$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$133.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void userData$set(MemorySegment seg, long index, MemorySegment x) {
        constants$133.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle internalValue$VH() {
        return constants$134.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static int internalValue$get(MemorySegment seg) {
        return (int)constants$134.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static void internalValue$set(MemorySegment seg, int x) {
        constants$134.const$0.set(seg, x);
    }
    public static int internalValue$get(MemorySegment seg, long index) {
        return (int)constants$134.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void internalValue$set(MemorySegment seg, long index, int x) {
        constants$134.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


