// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Profile {
 *     float step;
 *     float pairs;
 *     float collide;
 *     float solve;
 *     float mergeIslands;
 *     float prepareStages;
 *     float solveConstraints;
 *     float prepareConstraints;
 *     float integrateVelocities;
 *     float warmStart;
 *     float solveImpulses;
 *     float integratePositions;
 *     float relaxImpulses;
 *     float applyRestitution;
 *     float storeImpulses;
 *     float splitIslands;
 *     float transforms;
 *     float hitEvents;
 *     float refit;
 *     float bullets;
 *     float sleepIslands;
 *     float sensors;
 * };
 * }
 */
public class b2Profile {

    public static MemoryLayout $LAYOUT() {
        return constants$119.const$2;
    }
    public static VarHandle step$VH() {
        return constants$119.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float step;
     * }
     */
    public static float step$get(MemorySegment seg) {
        return (float)constants$119.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float step;
     * }
     */
    public static void step$set(MemorySegment seg, float x) {
        constants$119.const$3.set(seg, x);
    }
    public static float step$get(MemorySegment seg, long index) {
        return (float)constants$119.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void step$set(MemorySegment seg, long index, float x) {
        constants$119.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle pairs$VH() {
        return constants$119.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float pairs;
     * }
     */
    public static float pairs$get(MemorySegment seg) {
        return (float)constants$119.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float pairs;
     * }
     */
    public static void pairs$set(MemorySegment seg, float x) {
        constants$119.const$4.set(seg, x);
    }
    public static float pairs$get(MemorySegment seg, long index) {
        return (float)constants$119.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void pairs$set(MemorySegment seg, long index, float x) {
        constants$119.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle collide$VH() {
        return constants$119.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float collide;
     * }
     */
    public static float collide$get(MemorySegment seg) {
        return (float)constants$119.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float collide;
     * }
     */
    public static void collide$set(MemorySegment seg, float x) {
        constants$119.const$5.set(seg, x);
    }
    public static float collide$get(MemorySegment seg, long index) {
        return (float)constants$119.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void collide$set(MemorySegment seg, long index, float x) {
        constants$119.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle solve$VH() {
        return constants$120.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float solve;
     * }
     */
    public static float solve$get(MemorySegment seg) {
        return (float)constants$120.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float solve;
     * }
     */
    public static void solve$set(MemorySegment seg, float x) {
        constants$120.const$0.set(seg, x);
    }
    public static float solve$get(MemorySegment seg, long index) {
        return (float)constants$120.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void solve$set(MemorySegment seg, long index, float x) {
        constants$120.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mergeIslands$VH() {
        return constants$120.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float mergeIslands;
     * }
     */
    public static float mergeIslands$get(MemorySegment seg) {
        return (float)constants$120.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float mergeIslands;
     * }
     */
    public static void mergeIslands$set(MemorySegment seg, float x) {
        constants$120.const$1.set(seg, x);
    }
    public static float mergeIslands$get(MemorySegment seg, long index) {
        return (float)constants$120.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void mergeIslands$set(MemorySegment seg, long index, float x) {
        constants$120.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle prepareStages$VH() {
        return constants$120.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float prepareStages;
     * }
     */
    public static float prepareStages$get(MemorySegment seg) {
        return (float)constants$120.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float prepareStages;
     * }
     */
    public static void prepareStages$set(MemorySegment seg, float x) {
        constants$120.const$2.set(seg, x);
    }
    public static float prepareStages$get(MemorySegment seg, long index) {
        return (float)constants$120.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void prepareStages$set(MemorySegment seg, long index, float x) {
        constants$120.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle solveConstraints$VH() {
        return constants$120.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float solveConstraints;
     * }
     */
    public static float solveConstraints$get(MemorySegment seg) {
        return (float)constants$120.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float solveConstraints;
     * }
     */
    public static void solveConstraints$set(MemorySegment seg, float x) {
        constants$120.const$3.set(seg, x);
    }
    public static float solveConstraints$get(MemorySegment seg, long index) {
        return (float)constants$120.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void solveConstraints$set(MemorySegment seg, long index, float x) {
        constants$120.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle prepareConstraints$VH() {
        return constants$120.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float prepareConstraints;
     * }
     */
    public static float prepareConstraints$get(MemorySegment seg) {
        return (float)constants$120.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float prepareConstraints;
     * }
     */
    public static void prepareConstraints$set(MemorySegment seg, float x) {
        constants$120.const$4.set(seg, x);
    }
    public static float prepareConstraints$get(MemorySegment seg, long index) {
        return (float)constants$120.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void prepareConstraints$set(MemorySegment seg, long index, float x) {
        constants$120.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle integrateVelocities$VH() {
        return constants$120.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float integrateVelocities;
     * }
     */
    public static float integrateVelocities$get(MemorySegment seg) {
        return (float)constants$120.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float integrateVelocities;
     * }
     */
    public static void integrateVelocities$set(MemorySegment seg, float x) {
        constants$120.const$5.set(seg, x);
    }
    public static float integrateVelocities$get(MemorySegment seg, long index) {
        return (float)constants$120.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void integrateVelocities$set(MemorySegment seg, long index, float x) {
        constants$120.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle warmStart$VH() {
        return constants$121.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float warmStart;
     * }
     */
    public static float warmStart$get(MemorySegment seg) {
        return (float)constants$121.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float warmStart;
     * }
     */
    public static void warmStart$set(MemorySegment seg, float x) {
        constants$121.const$0.set(seg, x);
    }
    public static float warmStart$get(MemorySegment seg, long index) {
        return (float)constants$121.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void warmStart$set(MemorySegment seg, long index, float x) {
        constants$121.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle solveImpulses$VH() {
        return constants$121.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float solveImpulses;
     * }
     */
    public static float solveImpulses$get(MemorySegment seg) {
        return (float)constants$121.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float solveImpulses;
     * }
     */
    public static void solveImpulses$set(MemorySegment seg, float x) {
        constants$121.const$1.set(seg, x);
    }
    public static float solveImpulses$get(MemorySegment seg, long index) {
        return (float)constants$121.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void solveImpulses$set(MemorySegment seg, long index, float x) {
        constants$121.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle integratePositions$VH() {
        return constants$121.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float integratePositions;
     * }
     */
    public static float integratePositions$get(MemorySegment seg) {
        return (float)constants$121.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float integratePositions;
     * }
     */
    public static void integratePositions$set(MemorySegment seg, float x) {
        constants$121.const$2.set(seg, x);
    }
    public static float integratePositions$get(MemorySegment seg, long index) {
        return (float)constants$121.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void integratePositions$set(MemorySegment seg, long index, float x) {
        constants$121.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle relaxImpulses$VH() {
        return constants$121.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float relaxImpulses;
     * }
     */
    public static float relaxImpulses$get(MemorySegment seg) {
        return (float)constants$121.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float relaxImpulses;
     * }
     */
    public static void relaxImpulses$set(MemorySegment seg, float x) {
        constants$121.const$3.set(seg, x);
    }
    public static float relaxImpulses$get(MemorySegment seg, long index) {
        return (float)constants$121.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void relaxImpulses$set(MemorySegment seg, long index, float x) {
        constants$121.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle applyRestitution$VH() {
        return constants$121.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float applyRestitution;
     * }
     */
    public static float applyRestitution$get(MemorySegment seg) {
        return (float)constants$121.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float applyRestitution;
     * }
     */
    public static void applyRestitution$set(MemorySegment seg, float x) {
        constants$121.const$4.set(seg, x);
    }
    public static float applyRestitution$get(MemorySegment seg, long index) {
        return (float)constants$121.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void applyRestitution$set(MemorySegment seg, long index, float x) {
        constants$121.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle storeImpulses$VH() {
        return constants$121.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float storeImpulses;
     * }
     */
    public static float storeImpulses$get(MemorySegment seg) {
        return (float)constants$121.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float storeImpulses;
     * }
     */
    public static void storeImpulses$set(MemorySegment seg, float x) {
        constants$121.const$5.set(seg, x);
    }
    public static float storeImpulses$get(MemorySegment seg, long index) {
        return (float)constants$121.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void storeImpulses$set(MemorySegment seg, long index, float x) {
        constants$121.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle splitIslands$VH() {
        return constants$122.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float splitIslands;
     * }
     */
    public static float splitIslands$get(MemorySegment seg) {
        return (float)constants$122.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float splitIslands;
     * }
     */
    public static void splitIslands$set(MemorySegment seg, float x) {
        constants$122.const$0.set(seg, x);
    }
    public static float splitIslands$get(MemorySegment seg, long index) {
        return (float)constants$122.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void splitIslands$set(MemorySegment seg, long index, float x) {
        constants$122.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle transforms$VH() {
        return constants$122.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float transforms;
     * }
     */
    public static float transforms$get(MemorySegment seg) {
        return (float)constants$122.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float transforms;
     * }
     */
    public static void transforms$set(MemorySegment seg, float x) {
        constants$122.const$1.set(seg, x);
    }
    public static float transforms$get(MemorySegment seg, long index) {
        return (float)constants$122.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void transforms$set(MemorySegment seg, long index, float x) {
        constants$122.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hitEvents$VH() {
        return constants$122.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hitEvents;
     * }
     */
    public static float hitEvents$get(MemorySegment seg) {
        return (float)constants$122.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hitEvents;
     * }
     */
    public static void hitEvents$set(MemorySegment seg, float x) {
        constants$122.const$2.set(seg, x);
    }
    public static float hitEvents$get(MemorySegment seg, long index) {
        return (float)constants$122.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void hitEvents$set(MemorySegment seg, long index, float x) {
        constants$122.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle refit$VH() {
        return constants$122.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float refit;
     * }
     */
    public static float refit$get(MemorySegment seg) {
        return (float)constants$122.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float refit;
     * }
     */
    public static void refit$set(MemorySegment seg, float x) {
        constants$122.const$3.set(seg, x);
    }
    public static float refit$get(MemorySegment seg, long index) {
        return (float)constants$122.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void refit$set(MemorySegment seg, long index, float x) {
        constants$122.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle bullets$VH() {
        return constants$122.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float bullets;
     * }
     */
    public static float bullets$get(MemorySegment seg) {
        return (float)constants$122.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float bullets;
     * }
     */
    public static void bullets$set(MemorySegment seg, float x) {
        constants$122.const$4.set(seg, x);
    }
    public static float bullets$get(MemorySegment seg, long index) {
        return (float)constants$122.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void bullets$set(MemorySegment seg, long index, float x) {
        constants$122.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sleepIslands$VH() {
        return constants$122.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float sleepIslands;
     * }
     */
    public static float sleepIslands$get(MemorySegment seg) {
        return (float)constants$122.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float sleepIslands;
     * }
     */
    public static void sleepIslands$set(MemorySegment seg, float x) {
        constants$122.const$5.set(seg, x);
    }
    public static float sleepIslands$get(MemorySegment seg, long index) {
        return (float)constants$122.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void sleepIslands$set(MemorySegment seg, long index, float x) {
        constants$122.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sensors$VH() {
        return constants$123.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float sensors;
     * }
     */
    public static float sensors$get(MemorySegment seg) {
        return (float)constants$123.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float sensors;
     * }
     */
    public static void sensors$set(MemorySegment seg, float x) {
        constants$123.const$0.set(seg, x);
    }
    public static float sensors$get(MemorySegment seg, long index) {
        return (float)constants$123.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void sensors$set(MemorySegment seg, long index, float x) {
        constants$123.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


