// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2RayCastInput {
 *     struct b2Vec2 origin;
 *     struct b2Vec2 translation;
 *     float maxFraction;
 * };
 * }
 */
public class b2RayCastInput {

    public static MemoryLayout $LAYOUT() {
        return constants$66.const$0;
    }
    public static MemorySegment origin$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment translation$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static VarHandle maxFraction$VH() {
        return constants$66.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxFraction;
     * }
     */
    public static float maxFraction$get(MemorySegment seg) {
        return (float)constants$66.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxFraction;
     * }
     */
    public static void maxFraction$set(MemorySegment seg, float x) {
        constants$66.const$1.set(seg, x);
    }
    public static float maxFraction$get(MemorySegment seg, long index) {
        return (float)constants$66.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void maxFraction$set(MemorySegment seg, long index, float x) {
        constants$66.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


