// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Rot {
 *     float c;
 *     float s;
 * };
 * }
 */
public class b2Rot {

    public static MemoryLayout $LAYOUT() {
        return constants$61.const$4;
    }
    public static VarHandle c$VH() {
        return constants$61.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float c;
     * }
     */
    public static float c$get(MemorySegment seg) {
        return (float)constants$61.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float c;
     * }
     */
    public static void c$set(MemorySegment seg, float x) {
        constants$61.const$5.set(seg, x);
    }
    public static float c$get(MemorySegment seg, long index) {
        return (float)constants$61.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void c$set(MemorySegment seg, long index, float x) {
        constants$61.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle s$VH() {
        return constants$62.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float s;
     * }
     */
    public static float s$get(MemorySegment seg) {
        return (float)constants$62.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float s;
     * }
     */
    public static void s$set(MemorySegment seg, float x) {
        constants$62.const$0.set(seg, x);
    }
    public static float s$get(MemorySegment seg, long index) {
        return (float)constants$62.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void s$set(MemorySegment seg, long index, float x) {
        constants$62.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


