// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * void* (*b2SetAllocator$allocFcn)(unsigned int,int);
 * }
 */
public interface b2SetAllocator$allocFcn {

    java.lang.foreign.MemorySegment apply(int size, int alignment);
    static MemorySegment allocate(b2SetAllocator$allocFcn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$2.const$5, fi, constants$1.const$3, scope);
    }
    static b2SetAllocator$allocFcn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (int _size, int _alignment) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$1.const$5.invokeExact(symbol, _size, _alignment);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


