// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2SegmentDistanceResult {
 *     struct b2Vec2 closest1;
 *     struct b2Vec2 closest2;
 *     float fraction1;
 *     float fraction2;
 *     float distanceSquared;
 * };
 * }
 */
public class b2SegmentDistanceResult {

    public static MemoryLayout $LAYOUT() {
        return constants$77.const$4;
    }
    public static MemorySegment closest1$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment closest2$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static VarHandle fraction1$VH() {
        return constants$77.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction1;
     * }
     */
    public static float fraction1$get(MemorySegment seg) {
        return (float)constants$77.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction1;
     * }
     */
    public static void fraction1$set(MemorySegment seg, float x) {
        constants$77.const$5.set(seg, x);
    }
    public static float fraction1$get(MemorySegment seg, long index) {
        return (float)constants$77.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void fraction1$set(MemorySegment seg, long index, float x) {
        constants$77.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fraction2$VH() {
        return constants$78.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction2;
     * }
     */
    public static float fraction2$get(MemorySegment seg) {
        return (float)constants$78.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction2;
     * }
     */
    public static void fraction2$set(MemorySegment seg, float x) {
        constants$78.const$0.set(seg, x);
    }
    public static float fraction2$get(MemorySegment seg, long index) {
        return (float)constants$78.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void fraction2$set(MemorySegment seg, long index, float x) {
        constants$78.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle distanceSquared$VH() {
        return constants$78.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float distanceSquared;
     * }
     */
    public static float distanceSquared$get(MemorySegment seg) {
        return (float)constants$78.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float distanceSquared;
     * }
     */
    public static void distanceSquared$set(MemorySegment seg, float x) {
        constants$78.const$1.set(seg, x);
    }
    public static float distanceSquared$get(MemorySegment seg, long index) {
        return (float)constants$78.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void distanceSquared$set(MemorySegment seg, long index, float x) {
        constants$78.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


