// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2SimplexCache {
 *     unsigned short count;
 *     unsigned char indexA[3];
 *     unsigned char indexB[3];
 * };
 * }
 */
public class b2SimplexCache {

    public static MemoryLayout $LAYOUT() {
        return constants$78.const$4;
    }
    public static VarHandle count$VH() {
        return constants$78.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned short count;
     * }
     */
    public static short count$get(MemorySegment seg) {
        return (short)constants$78.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned short count;
     * }
     */
    public static void count$set(MemorySegment seg, short x) {
        constants$78.const$5.set(seg, x);
    }
    public static short count$get(MemorySegment seg, long index) {
        return (short)constants$78.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, short x) {
        constants$78.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment indexA$slice(MemorySegment seg) {
        return seg.asSlice(2, 3);
    }
    public static MemorySegment indexB$slice(MemorySegment seg) {
        return seg.asSlice(5, 3);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


