// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Simplex {
 *     struct b2SimplexVertex v1;
 *     struct b2SimplexVertex v2;
 *     struct b2SimplexVertex v3;
 *     int count;
 * };
 * }
 */
public class b2Simplex {

    public static MemoryLayout $LAYOUT() {
        return constants$80.const$4;
    }
    public static MemorySegment v1$slice(MemorySegment seg) {
        return seg.asSlice(0, 36);
    }
    public static MemorySegment v2$slice(MemorySegment seg) {
        return seg.asSlice(36, 36);
    }
    public static MemorySegment v3$slice(MemorySegment seg) {
        return seg.asSlice(72, 36);
    }
    public static VarHandle count$VH() {
        return constants$80.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int count;
     * }
     */
    public static int count$get(MemorySegment seg) {
        return (int)constants$80.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int count;
     * }
     */
    public static void count$set(MemorySegment seg, int x) {
        constants$80.const$5.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)constants$80.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        constants$80.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


