// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2Sweep {
 *     struct b2Vec2 localCenter;
 *     struct b2Vec2 c1;
 *     struct b2Vec2 c2;
 *     struct b2Rot q1;
 *     struct b2Rot q2;
 * };
 * }
 */
public class b2Sweep {

    public static MemoryLayout $LAYOUT() {
        return constants$82.const$4;
    }
    public static MemorySegment localCenter$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment c1$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static MemorySegment c2$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment q1$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static MemorySegment q2$slice(MemorySegment seg) {
        return seg.asSlice(32, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


