// Generated by jextract

package org.box2d;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef void (b2TaskCallback)(int, int, uint32_t, void *)
 * }
 */
public final class b2TaskCallback {

    private b2TaskCallback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(int startIndex, int endIndex, int workerIndex, MemorySegment taskContext);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        Box2D.C_INT,
        Box2D.C_INT,
        Box2D.C_INT,
        Box2D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box2D.upcallHandle(b2TaskCallback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(b2TaskCallback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr, int startIndex, int endIndex, int workerIndex, MemorySegment taskContext) {
        try {
             DOWN$MH.invokeExact(funcPtr, startIndex, endIndex, workerIndex, taskContext);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

