// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2TOIOutput {
 *     enum b2TOIState state;
 *     float fraction;
 * };
 * }
 */
public class b2TOIOutput {

    public static MemoryLayout $LAYOUT() {
        return constants$83.const$2;
    }
    public static VarHandle state$VH() {
        return constants$83.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * enum b2TOIState state;
     * }
     */
    public static int state$get(MemorySegment seg) {
        return (int)constants$83.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * enum b2TOIState state;
     * }
     */
    public static void state$set(MemorySegment seg, int x) {
        constants$83.const$3.set(seg, x);
    }
    public static int state$get(MemorySegment seg, long index) {
        return (int)constants$83.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void state$set(MemorySegment seg, long index, int x) {
        constants$83.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle fraction$VH() {
        return constants$83.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction;
     * }
     */
    public static float fraction$get(MemorySegment seg) {
        return (float)constants$83.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction;
     * }
     */
    public static void fraction$set(MemorySegment seg, float x) {
        constants$83.const$4.set(seg, x);
    }
    public static float fraction$get(MemorySegment seg, long index) {
        return (float)constants$83.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void fraction$set(MemorySegment seg, long index, float x) {
        constants$83.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


