// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2WeldJointDef {
 *     struct b2BodyId bodyIdA;
 *     struct b2BodyId bodyIdB;
 *     struct b2Vec2 localAnchorA;
 *     struct b2Vec2 localAnchorB;
 *     float referenceAngle;
 *     float linearHertz;
 *     float angularHertz;
 *     float linearDampingRatio;
 *     float angularDampingRatio;
 *     _Bool collideConnected;
 *     void* userData;
 *     int internalValue;
 * };
 * }
 */
public class b2WeldJointDef {

    public static MemoryLayout $LAYOUT() {
        return constants$137.const$3;
    }
    public static MemorySegment bodyIdA$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static MemorySegment bodyIdB$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static MemorySegment localAnchorA$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static MemorySegment localAnchorB$slice(MemorySegment seg) {
        return seg.asSlice(24, 8);
    }
    public static VarHandle referenceAngle$VH() {
        return constants$137.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float referenceAngle;
     * }
     */
    public static float referenceAngle$get(MemorySegment seg) {
        return (float)constants$137.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float referenceAngle;
     * }
     */
    public static void referenceAngle$set(MemorySegment seg, float x) {
        constants$137.const$4.set(seg, x);
    }
    public static float referenceAngle$get(MemorySegment seg, long index) {
        return (float)constants$137.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void referenceAngle$set(MemorySegment seg, long index, float x) {
        constants$137.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle linearHertz$VH() {
        return constants$137.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float linearHertz;
     * }
     */
    public static float linearHertz$get(MemorySegment seg) {
        return (float)constants$137.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float linearHertz;
     * }
     */
    public static void linearHertz$set(MemorySegment seg, float x) {
        constants$137.const$5.set(seg, x);
    }
    public static float linearHertz$get(MemorySegment seg, long index) {
        return (float)constants$137.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void linearHertz$set(MemorySegment seg, long index, float x) {
        constants$137.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle angularHertz$VH() {
        return constants$138.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float angularHertz;
     * }
     */
    public static float angularHertz$get(MemorySegment seg) {
        return (float)constants$138.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float angularHertz;
     * }
     */
    public static void angularHertz$set(MemorySegment seg, float x) {
        constants$138.const$0.set(seg, x);
    }
    public static float angularHertz$get(MemorySegment seg, long index) {
        return (float)constants$138.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void angularHertz$set(MemorySegment seg, long index, float x) {
        constants$138.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle linearDampingRatio$VH() {
        return constants$138.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float linearDampingRatio;
     * }
     */
    public static float linearDampingRatio$get(MemorySegment seg) {
        return (float)constants$138.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float linearDampingRatio;
     * }
     */
    public static void linearDampingRatio$set(MemorySegment seg, float x) {
        constants$138.const$1.set(seg, x);
    }
    public static float linearDampingRatio$get(MemorySegment seg, long index) {
        return (float)constants$138.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void linearDampingRatio$set(MemorySegment seg, long index, float x) {
        constants$138.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle angularDampingRatio$VH() {
        return constants$138.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float angularDampingRatio;
     * }
     */
    public static float angularDampingRatio$get(MemorySegment seg) {
        return (float)constants$138.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float angularDampingRatio;
     * }
     */
    public static void angularDampingRatio$set(MemorySegment seg, float x) {
        constants$138.const$2.set(seg, x);
    }
    public static float angularDampingRatio$get(MemorySegment seg, long index) {
        return (float)constants$138.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void angularDampingRatio$set(MemorySegment seg, long index, float x) {
        constants$138.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle collideConnected$VH() {
        return constants$138.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool collideConnected;
     * }
     */
    public static boolean collideConnected$get(MemorySegment seg) {
        return (boolean)constants$138.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool collideConnected;
     * }
     */
    public static void collideConnected$set(MemorySegment seg, boolean x) {
        constants$138.const$3.set(seg, x);
    }
    public static boolean collideConnected$get(MemorySegment seg, long index) {
        return (boolean)constants$138.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void collideConnected$set(MemorySegment seg, long index, boolean x) {
        constants$138.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle userData$VH() {
        return constants$138.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static MemorySegment userData$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$138.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static void userData$set(MemorySegment seg, MemorySegment x) {
        constants$138.const$4.set(seg, x);
    }
    public static MemorySegment userData$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$138.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void userData$set(MemorySegment seg, long index, MemorySegment x) {
        constants$138.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle internalValue$VH() {
        return constants$138.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static int internalValue$get(MemorySegment seg) {
        return (int)constants$138.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static void internalValue$set(MemorySegment seg, int x) {
        constants$138.const$5.set(seg, x);
    }
    public static int internalValue$get(MemorySegment seg, long index) {
        return (int)constants$138.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void internalValue$set(MemorySegment seg, long index, int x) {
        constants$138.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


