// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * struct b2WorldDef {
 *     struct b2Vec2 gravity;
 *     float restitutionThreshold;
 *     float hitEventThreshold;
 *     float contactHertz;
 *     float contactDampingRatio;
 *     float maxContactPushSpeed;
 *     float maximumLinearSpeed;
 *     float (*frictionCallback)(float,int,float,int);
 *     float (*restitutionCallback)(float,int,float,int);
 *     _Bool enableSleep;
 *     _Bool enableContinuous;
 *     int workerCount;
 *     void* (*enqueueTask)(void (*)(int,int,unsigned int,void*),int,int,void*,void*);
 *     void (*finishTask)(void*,void*);
 *     void* userTaskContext;
 *     void* userData;
 *     int internalValue;
 * };
 * }
 */
public class b2WorldDef {

    public static MemoryLayout $LAYOUT() {
        return constants$105.const$2;
    }
    public static MemorySegment gravity$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    public static VarHandle restitutionThreshold$VH() {
        return constants$105.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float restitutionThreshold;
     * }
     */
    public static float restitutionThreshold$get(MemorySegment seg) {
        return (float)constants$105.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float restitutionThreshold;
     * }
     */
    public static void restitutionThreshold$set(MemorySegment seg, float x) {
        constants$105.const$3.set(seg, x);
    }
    public static float restitutionThreshold$get(MemorySegment seg, long index) {
        return (float)constants$105.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void restitutionThreshold$set(MemorySegment seg, long index, float x) {
        constants$105.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle hitEventThreshold$VH() {
        return constants$105.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float hitEventThreshold;
     * }
     */
    public static float hitEventThreshold$get(MemorySegment seg) {
        return (float)constants$105.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float hitEventThreshold;
     * }
     */
    public static void hitEventThreshold$set(MemorySegment seg, float x) {
        constants$105.const$4.set(seg, x);
    }
    public static float hitEventThreshold$get(MemorySegment seg, long index) {
        return (float)constants$105.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void hitEventThreshold$set(MemorySegment seg, long index, float x) {
        constants$105.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle contactHertz$VH() {
        return constants$105.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float contactHertz;
     * }
     */
    public static float contactHertz$get(MemorySegment seg) {
        return (float)constants$105.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float contactHertz;
     * }
     */
    public static void contactHertz$set(MemorySegment seg, float x) {
        constants$105.const$5.set(seg, x);
    }
    public static float contactHertz$get(MemorySegment seg, long index) {
        return (float)constants$105.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void contactHertz$set(MemorySegment seg, long index, float x) {
        constants$105.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle contactDampingRatio$VH() {
        return constants$106.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float contactDampingRatio;
     * }
     */
    public static float contactDampingRatio$get(MemorySegment seg) {
        return (float)constants$106.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float contactDampingRatio;
     * }
     */
    public static void contactDampingRatio$set(MemorySegment seg, float x) {
        constants$106.const$0.set(seg, x);
    }
    public static float contactDampingRatio$get(MemorySegment seg, long index) {
        return (float)constants$106.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void contactDampingRatio$set(MemorySegment seg, long index, float x) {
        constants$106.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maxContactPushSpeed$VH() {
        return constants$106.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maxContactPushSpeed;
     * }
     */
    public static float maxContactPushSpeed$get(MemorySegment seg) {
        return (float)constants$106.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maxContactPushSpeed;
     * }
     */
    public static void maxContactPushSpeed$set(MemorySegment seg, float x) {
        constants$106.const$1.set(seg, x);
    }
    public static float maxContactPushSpeed$get(MemorySegment seg, long index) {
        return (float)constants$106.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void maxContactPushSpeed$set(MemorySegment seg, long index, float x) {
        constants$106.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle maximumLinearSpeed$VH() {
        return constants$106.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed;
     * }
     */
    public static float maximumLinearSpeed$get(MemorySegment seg) {
        return (float)constants$106.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float maximumLinearSpeed;
     * }
     */
    public static void maximumLinearSpeed$set(MemorySegment seg, float x) {
        constants$106.const$2.set(seg, x);
    }
    public static float maximumLinearSpeed$get(MemorySegment seg, long index) {
        return (float)constants$106.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void maximumLinearSpeed$set(MemorySegment seg, long index, float x) {
        constants$106.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet lang=c :
 * float (*frictionCallback)(float,int,float,int);
     * }
     */
    public interface frictionCallback {

        float apply(float restitutionA, int userMaterialIdA, float restitutionB, int userMaterialIdB);
        static MemorySegment allocate(frictionCallback fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$106.const$3, fi, constants$103.const$5, scope);
        }
        static frictionCallback ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (float _restitutionA, int _userMaterialIdA, float _restitutionB, int _userMaterialIdB) -> {
                try {
                    return (float)constants$104.const$1.invokeExact(symbol, _restitutionA, _userMaterialIdA, _restitutionB, _userMaterialIdB);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle frictionCallback$VH() {
        return constants$106.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float (*frictionCallback)(float,int,float,int);
     * }
     */
    public static MemorySegment frictionCallback$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$106.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float (*frictionCallback)(float,int,float,int);
     * }
     */
    public static void frictionCallback$set(MemorySegment seg, MemorySegment x) {
        constants$106.const$4.set(seg, x);
    }
    public static MemorySegment frictionCallback$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$106.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void frictionCallback$set(MemorySegment seg, long index, MemorySegment x) {
        constants$106.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static frictionCallback frictionCallback(MemorySegment segment, Arena scope) {
        return frictionCallback.ofAddress(frictionCallback$get(segment), scope);
    }
    /**
     * {@snippet lang=c :
 * float (*restitutionCallback)(float,int,float,int);
     * }
     */
    public interface restitutionCallback {

        float apply(float restitutionA, int userMaterialIdA, float restitutionB, int userMaterialIdB);
        static MemorySegment allocate(restitutionCallback fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$106.const$5, fi, constants$103.const$5, scope);
        }
        static restitutionCallback ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (float _restitutionA, int _userMaterialIdA, float _restitutionB, int _userMaterialIdB) -> {
                try {
                    return (float)constants$104.const$1.invokeExact(symbol, _restitutionA, _userMaterialIdA, _restitutionB, _userMaterialIdB);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle restitutionCallback$VH() {
        return constants$107.const$0;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * float (*restitutionCallback)(float,int,float,int);
     * }
     */
    public static MemorySegment restitutionCallback$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$107.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * float (*restitutionCallback)(float,int,float,int);
     * }
     */
    public static void restitutionCallback$set(MemorySegment seg, MemorySegment x) {
        constants$107.const$0.set(seg, x);
    }
    public static MemorySegment restitutionCallback$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$107.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void restitutionCallback$set(MemorySegment seg, long index, MemorySegment x) {
        constants$107.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static restitutionCallback restitutionCallback(MemorySegment segment, Arena scope) {
        return restitutionCallback.ofAddress(restitutionCallback$get(segment), scope);
    }
    public static VarHandle enableSleep$VH() {
        return constants$107.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableSleep;
     * }
     */
    public static boolean enableSleep$get(MemorySegment seg) {
        return (boolean)constants$107.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableSleep;
     * }
     */
    public static void enableSleep$set(MemorySegment seg, boolean x) {
        constants$107.const$1.set(seg, x);
    }
    public static boolean enableSleep$get(MemorySegment seg, long index) {
        return (boolean)constants$107.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void enableSleep$set(MemorySegment seg, long index, boolean x) {
        constants$107.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle enableContinuous$VH() {
        return constants$107.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool enableContinuous;
     * }
     */
    public static boolean enableContinuous$get(MemorySegment seg) {
        return (boolean)constants$107.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool enableContinuous;
     * }
     */
    public static void enableContinuous$set(MemorySegment seg, boolean x) {
        constants$107.const$2.set(seg, x);
    }
    public static boolean enableContinuous$get(MemorySegment seg, long index) {
        return (boolean)constants$107.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void enableContinuous$set(MemorySegment seg, long index, boolean x) {
        constants$107.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle workerCount$VH() {
        return constants$107.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int workerCount;
     * }
     */
    public static int workerCount$get(MemorySegment seg) {
        return (int)constants$107.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int workerCount;
     * }
     */
    public static void workerCount$set(MemorySegment seg, int x) {
        constants$107.const$3.set(seg, x);
    }
    public static int workerCount$get(MemorySegment seg, long index) {
        return (int)constants$107.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void workerCount$set(MemorySegment seg, long index, int x) {
        constants$107.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet lang=c :
 * void* (*enqueueTask)(void (*)(int,int,unsigned int,void*),int,int,void*,void*);
     * }
     */
    public interface enqueueTask {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemorySegment task, int itemCount, int minRange, java.lang.foreign.MemorySegment taskContext, java.lang.foreign.MemorySegment userContext);
        static MemorySegment allocate(enqueueTask fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$107.const$4, fi, constants$103.const$0, scope);
        }
        static enqueueTask ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment _task, int _itemCount, int _minRange, java.lang.foreign.MemorySegment _taskContext, java.lang.foreign.MemorySegment _userContext) -> {
                try {
                    return (java.lang.foreign.MemorySegment)constants$103.const$2.invokeExact(symbol, _task, _itemCount, _minRange, _taskContext, _userContext);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle enqueueTask$VH() {
        return constants$107.const$5;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* (*enqueueTask)(void (*)(int,int,unsigned int,void*),int,int,void*,void*);
     * }
     */
    public static MemorySegment enqueueTask$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$107.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* (*enqueueTask)(void (*)(int,int,unsigned int,void*),int,int,void*,void*);
     * }
     */
    public static void enqueueTask$set(MemorySegment seg, MemorySegment x) {
        constants$107.const$5.set(seg, x);
    }
    public static MemorySegment enqueueTask$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$107.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void enqueueTask$set(MemorySegment seg, long index, MemorySegment x) {
        constants$107.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static enqueueTask enqueueTask(MemorySegment segment, Arena scope) {
        return enqueueTask.ofAddress(enqueueTask$get(segment), scope);
    }
    /**
     * {@snippet lang=c :
 * void (*finishTask)(void*,void*);
     * }
     */
    public interface finishTask {

        void apply(java.lang.foreign.MemorySegment userTask, java.lang.foreign.MemorySegment userContext);
        static MemorySegment allocate(finishTask fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$108.const$0, fi, constants$3.const$1, scope);
        }
        static finishTask ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment _userTask, java.lang.foreign.MemorySegment _userContext) -> {
                try {
                    constants$103.const$4.invokeExact(symbol, _userTask, _userContext);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle finishTask$VH() {
        return constants$108.const$1;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*finishTask)(void*,void*);
     * }
     */
    public static MemorySegment finishTask$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*finishTask)(void*,void*);
     * }
     */
    public static void finishTask$set(MemorySegment seg, MemorySegment x) {
        constants$108.const$1.set(seg, x);
    }
    public static MemorySegment finishTask$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void finishTask$set(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static finishTask finishTask(MemorySegment segment, Arena scope) {
        return finishTask.ofAddress(finishTask$get(segment), scope);
    }
    public static VarHandle userTaskContext$VH() {
        return constants$108.const$2;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* userTaskContext;
     * }
     */
    public static MemorySegment userTaskContext$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* userTaskContext;
     * }
     */
    public static void userTaskContext$set(MemorySegment seg, MemorySegment x) {
        constants$108.const$2.set(seg, x);
    }
    public static MemorySegment userTaskContext$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void userTaskContext$set(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle userData$VH() {
        return constants$108.const$3;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static MemorySegment userData$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$108.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * void* userData;
     * }
     */
    public static void userData$set(MemorySegment seg, MemorySegment x) {
        constants$108.const$3.set(seg, x);
    }
    public static MemorySegment userData$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$108.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void userData$set(MemorySegment seg, long index, MemorySegment x) {
        constants$108.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle internalValue$VH() {
        return constants$108.const$4;
    }
    /**
     * Getter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static int internalValue$get(MemorySegment seg) {
        return (int)constants$108.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet lang=c :
     * int internalValue;
     * }
     */
    public static void internalValue$set(MemorySegment seg, int x) {
        constants$108.const$4.set(seg, x);
    }
    public static int internalValue$get(MemorySegment seg, long index) {
        return (int)constants$108.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void internalValue$set(MemorySegment seg, long index, int x) {
        constants$108.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


