// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * float (*b2World_SetFrictionCallback$callback)(float,int,float,int);
 * }
 */
public interface b2World_SetFrictionCallback$callback {

    float apply(float restitutionA, int userMaterialIdA, float restitutionB, int userMaterialIdB);
    static MemorySegment allocate(b2World_SetFrictionCallback$callback fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$169.const$3, fi, constants$103.const$5, scope);
    }
    static b2World_SetFrictionCallback$callback ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (float _restitutionA, int _userMaterialIdA, float _restitutionB, int _userMaterialIdB) -> {
            try {
                return (float)constants$104.const$1.invokeExact(symbol, _restitutionA, _userMaterialIdA, _restitutionB, _userMaterialIdB);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


