// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet lang=c :
 * _Bool (*b2World_SetPreSolveCallback$fcn)(struct b2ShapeId,struct b2ShapeId,struct b2Manifold*,void*);
 * }
 */
public interface b2World_SetPreSolveCallback$fcn {

    boolean apply(java.lang.foreign.MemorySegment shapeIdA, java.lang.foreign.MemorySegment shapeIdB, java.lang.foreign.MemorySegment manifold, java.lang.foreign.MemorySegment context);
    static MemorySegment allocate(b2World_SetPreSolveCallback$fcn fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$166.const$0, fi, constants$147.const$4, scope);
    }
    static b2World_SetPreSolveCallback$fcn ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _shapeIdA, java.lang.foreign.MemorySegment _shapeIdB, java.lang.foreign.MemorySegment _manifold, java.lang.foreign.MemorySegment _context) -> {
            try {
                return (boolean)constants$148.const$0.invokeExact(symbol, _shapeIdA, _shapeIdB, _manifold, _context);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


