// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class box2d_h_1 {

    public static MethodHandle b2RevoluteJoint_SetSpringHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$219.const$2,"b2RevoluteJoint_SetSpringHertz");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetSpringHertz(struct b2JointId jointId, float hertz);
     * }
     */
    public static void b2RevoluteJoint_SetSpringHertz(MemorySegment jointId, float hertz) {
        var mh$ = b2RevoluteJoint_SetSpringHertz$MH();
        try {
            mh$.invokeExact(jointId, hertz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetSpringHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$219.const$3,"b2RevoluteJoint_GetSpringHertz");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetSpringHertz(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetSpringHertz(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetSpringHertz$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_SetSpringDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$219.const$4,"b2RevoluteJoint_SetSpringDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetSpringDampingRatio(struct b2JointId jointId, float dampingRatio);
     * }
     */
    public static void b2RevoluteJoint_SetSpringDampingRatio(MemorySegment jointId, float dampingRatio) {
        var mh$ = b2RevoluteJoint_SetSpringDampingRatio$MH();
        try {
            mh$.invokeExact(jointId, dampingRatio);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetSpringDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$219.const$5,"b2RevoluteJoint_GetSpringDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetSpringDampingRatio(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetSpringDampingRatio(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetSpringDampingRatio$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_SetTargetAngle$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$0,"b2RevoluteJoint_SetTargetAngle");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetTargetAngle(struct b2JointId jointId, float angle);
     * }
     */
    public static void b2RevoluteJoint_SetTargetAngle(MemorySegment jointId, float angle) {
        var mh$ = b2RevoluteJoint_SetTargetAngle$MH();
        try {
            mh$.invokeExact(jointId, angle);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetTargetAngle$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$1,"b2RevoluteJoint_GetTargetAngle");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetTargetAngle(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetTargetAngle(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetTargetAngle$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetAngle$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$2,"b2RevoluteJoint_GetAngle");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetAngle(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetAngle(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetAngle$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_EnableLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$3,"b2RevoluteJoint_EnableLimit");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_EnableLimit(struct b2JointId jointId, _Bool enableLimit);
     * }
     */
    public static void b2RevoluteJoint_EnableLimit(MemorySegment jointId, boolean enableLimit) {
        var mh$ = b2RevoluteJoint_EnableLimit$MH();
        try {
            mh$.invokeExact(jointId, enableLimit);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_IsLimitEnabled$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$4,"b2RevoluteJoint_IsLimitEnabled");
    }
    /**
     * {@snippet lang=c :
     * _Bool b2RevoluteJoint_IsLimitEnabled(struct b2JointId jointId);
     * }
     */
    public static boolean b2RevoluteJoint_IsLimitEnabled(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_IsLimitEnabled$MH();
        try {
            return (boolean)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetLowerLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$220.const$5,"b2RevoluteJoint_GetLowerLimit");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetLowerLimit(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetLowerLimit(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetLowerLimit$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetUpperLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$0,"b2RevoluteJoint_GetUpperLimit");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetUpperLimit(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetUpperLimit(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetUpperLimit$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_SetLimits$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$1,"b2RevoluteJoint_SetLimits");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetLimits(struct b2JointId jointId, float lower, float upper);
     * }
     */
    public static void b2RevoluteJoint_SetLimits(MemorySegment jointId, float lower, float upper) {
        var mh$ = b2RevoluteJoint_SetLimits$MH();
        try {
            mh$.invokeExact(jointId, lower, upper);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_EnableMotor$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$2,"b2RevoluteJoint_EnableMotor");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_EnableMotor(struct b2JointId jointId, _Bool enableMotor);
     * }
     */
    public static void b2RevoluteJoint_EnableMotor(MemorySegment jointId, boolean enableMotor) {
        var mh$ = b2RevoluteJoint_EnableMotor$MH();
        try {
            mh$.invokeExact(jointId, enableMotor);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_IsMotorEnabled$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$3,"b2RevoluteJoint_IsMotorEnabled");
    }
    /**
     * {@snippet lang=c :
     * _Bool b2RevoluteJoint_IsMotorEnabled(struct b2JointId jointId);
     * }
     */
    public static boolean b2RevoluteJoint_IsMotorEnabled(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_IsMotorEnabled$MH();
        try {
            return (boolean)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_SetMotorSpeed$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$4,"b2RevoluteJoint_SetMotorSpeed");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetMotorSpeed(struct b2JointId jointId, float motorSpeed);
     * }
     */
    public static void b2RevoluteJoint_SetMotorSpeed(MemorySegment jointId, float motorSpeed) {
        var mh$ = b2RevoluteJoint_SetMotorSpeed$MH();
        try {
            mh$.invokeExact(jointId, motorSpeed);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetMotorSpeed$MH() {
        return RuntimeHelper.requireNonNull(constants$221.const$5,"b2RevoluteJoint_GetMotorSpeed");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetMotorSpeed(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetMotorSpeed(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetMotorSpeed$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$0,"b2RevoluteJoint_GetMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetMotorTorque(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetMotorTorque(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetMotorTorque$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_SetMaxMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$1,"b2RevoluteJoint_SetMaxMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * void b2RevoluteJoint_SetMaxMotorTorque(struct b2JointId jointId, float torque);
     * }
     */
    public static void b2RevoluteJoint_SetMaxMotorTorque(MemorySegment jointId, float torque) {
        var mh$ = b2RevoluteJoint_SetMaxMotorTorque$MH();
        try {
            mh$.invokeExact(jointId, torque);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2RevoluteJoint_GetMaxMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$2,"b2RevoluteJoint_GetMaxMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * float b2RevoluteJoint_GetMaxMotorTorque(struct b2JointId jointId);
     * }
     */
    public static float b2RevoluteJoint_GetMaxMotorTorque(MemorySegment jointId) {
        var mh$ = b2RevoluteJoint_GetMaxMotorTorque$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2CreateWeldJoint$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$3,"b2CreateWeldJoint");
    }
    /**
     * {@snippet lang=c :
     * struct b2JointId b2CreateWeldJoint(struct b2WorldId worldId, struct b2WeldJointDef* def);
     * }
     */
    public static MemorySegment b2CreateWeldJoint(SegmentAllocator allocator, MemorySegment worldId, MemorySegment def) {
        var mh$ = b2CreateWeldJoint$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(allocator, worldId, def);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_SetLinearHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$4,"b2WeldJoint_SetLinearHertz");
    }
    /**
     * {@snippet lang=c :
     * void b2WeldJoint_SetLinearHertz(struct b2JointId jointId, float hertz);
     * }
     */
    public static void b2WeldJoint_SetLinearHertz(MemorySegment jointId, float hertz) {
        var mh$ = b2WeldJoint_SetLinearHertz$MH();
        try {
            mh$.invokeExact(jointId, hertz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_GetLinearHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$222.const$5,"b2WeldJoint_GetLinearHertz");
    }
    /**
     * {@snippet lang=c :
     * float b2WeldJoint_GetLinearHertz(struct b2JointId jointId);
     * }
     */
    public static float b2WeldJoint_GetLinearHertz(MemorySegment jointId) {
        var mh$ = b2WeldJoint_GetLinearHertz$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_SetLinearDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$0,"b2WeldJoint_SetLinearDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * void b2WeldJoint_SetLinearDampingRatio(struct b2JointId jointId, float dampingRatio);
     * }
     */
    public static void b2WeldJoint_SetLinearDampingRatio(MemorySegment jointId, float dampingRatio) {
        var mh$ = b2WeldJoint_SetLinearDampingRatio$MH();
        try {
            mh$.invokeExact(jointId, dampingRatio);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_GetLinearDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$1,"b2WeldJoint_GetLinearDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * float b2WeldJoint_GetLinearDampingRatio(struct b2JointId jointId);
     * }
     */
    public static float b2WeldJoint_GetLinearDampingRatio(MemorySegment jointId) {
        var mh$ = b2WeldJoint_GetLinearDampingRatio$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_SetAngularHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$2,"b2WeldJoint_SetAngularHertz");
    }
    /**
     * {@snippet lang=c :
     * void b2WeldJoint_SetAngularHertz(struct b2JointId jointId, float hertz);
     * }
     */
    public static void b2WeldJoint_SetAngularHertz(MemorySegment jointId, float hertz) {
        var mh$ = b2WeldJoint_SetAngularHertz$MH();
        try {
            mh$.invokeExact(jointId, hertz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_GetAngularHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$3,"b2WeldJoint_GetAngularHertz");
    }
    /**
     * {@snippet lang=c :
     * float b2WeldJoint_GetAngularHertz(struct b2JointId jointId);
     * }
     */
    public static float b2WeldJoint_GetAngularHertz(MemorySegment jointId) {
        var mh$ = b2WeldJoint_GetAngularHertz$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_SetAngularDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$4,"b2WeldJoint_SetAngularDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * void b2WeldJoint_SetAngularDampingRatio(struct b2JointId jointId, float dampingRatio);
     * }
     */
    public static void b2WeldJoint_SetAngularDampingRatio(MemorySegment jointId, float dampingRatio) {
        var mh$ = b2WeldJoint_SetAngularDampingRatio$MH();
        try {
            mh$.invokeExact(jointId, dampingRatio);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WeldJoint_GetAngularDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$223.const$5,"b2WeldJoint_GetAngularDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * float b2WeldJoint_GetAngularDampingRatio(struct b2JointId jointId);
     * }
     */
    public static float b2WeldJoint_GetAngularDampingRatio(MemorySegment jointId) {
        var mh$ = b2WeldJoint_GetAngularDampingRatio$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2CreateWheelJoint$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$0,"b2CreateWheelJoint");
    }
    /**
     * {@snippet lang=c :
     * struct b2JointId b2CreateWheelJoint(struct b2WorldId worldId, struct b2WheelJointDef* def);
     * }
     */
    public static MemorySegment b2CreateWheelJoint(SegmentAllocator allocator, MemorySegment worldId, MemorySegment def) {
        var mh$ = b2CreateWheelJoint$MH();
        try {
            return (java.lang.foreign.MemorySegment)mh$.invokeExact(allocator, worldId, def);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_EnableSpring$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$1,"b2WheelJoint_EnableSpring");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_EnableSpring(struct b2JointId jointId, _Bool enableSpring);
     * }
     */
    public static void b2WheelJoint_EnableSpring(MemorySegment jointId, boolean enableSpring) {
        var mh$ = b2WheelJoint_EnableSpring$MH();
        try {
            mh$.invokeExact(jointId, enableSpring);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_IsSpringEnabled$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$2,"b2WheelJoint_IsSpringEnabled");
    }
    /**
     * {@snippet lang=c :
     * _Bool b2WheelJoint_IsSpringEnabled(struct b2JointId jointId);
     * }
     */
    public static boolean b2WheelJoint_IsSpringEnabled(MemorySegment jointId) {
        var mh$ = b2WheelJoint_IsSpringEnabled$MH();
        try {
            return (boolean)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_SetSpringHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$3,"b2WheelJoint_SetSpringHertz");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_SetSpringHertz(struct b2JointId jointId, float hertz);
     * }
     */
    public static void b2WheelJoint_SetSpringHertz(MemorySegment jointId, float hertz) {
        var mh$ = b2WheelJoint_SetSpringHertz$MH();
        try {
            mh$.invokeExact(jointId, hertz);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetSpringHertz$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$4,"b2WheelJoint_GetSpringHertz");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetSpringHertz(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetSpringHertz(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetSpringHertz$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_SetSpringDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$224.const$5,"b2WheelJoint_SetSpringDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_SetSpringDampingRatio(struct b2JointId jointId, float dampingRatio);
     * }
     */
    public static void b2WheelJoint_SetSpringDampingRatio(MemorySegment jointId, float dampingRatio) {
        var mh$ = b2WheelJoint_SetSpringDampingRatio$MH();
        try {
            mh$.invokeExact(jointId, dampingRatio);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetSpringDampingRatio$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$0,"b2WheelJoint_GetSpringDampingRatio");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetSpringDampingRatio(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetSpringDampingRatio(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetSpringDampingRatio$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_EnableLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$1,"b2WheelJoint_EnableLimit");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_EnableLimit(struct b2JointId jointId, _Bool enableLimit);
     * }
     */
    public static void b2WheelJoint_EnableLimit(MemorySegment jointId, boolean enableLimit) {
        var mh$ = b2WheelJoint_EnableLimit$MH();
        try {
            mh$.invokeExact(jointId, enableLimit);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_IsLimitEnabled$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$2,"b2WheelJoint_IsLimitEnabled");
    }
    /**
     * {@snippet lang=c :
     * _Bool b2WheelJoint_IsLimitEnabled(struct b2JointId jointId);
     * }
     */
    public static boolean b2WheelJoint_IsLimitEnabled(MemorySegment jointId) {
        var mh$ = b2WheelJoint_IsLimitEnabled$MH();
        try {
            return (boolean)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetLowerLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$3,"b2WheelJoint_GetLowerLimit");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetLowerLimit(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetLowerLimit(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetLowerLimit$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetUpperLimit$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$4,"b2WheelJoint_GetUpperLimit");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetUpperLimit(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetUpperLimit(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetUpperLimit$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_SetLimits$MH() {
        return RuntimeHelper.requireNonNull(constants$225.const$5,"b2WheelJoint_SetLimits");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_SetLimits(struct b2JointId jointId, float lower, float upper);
     * }
     */
    public static void b2WheelJoint_SetLimits(MemorySegment jointId, float lower, float upper) {
        var mh$ = b2WheelJoint_SetLimits$MH();
        try {
            mh$.invokeExact(jointId, lower, upper);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_EnableMotor$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$0,"b2WheelJoint_EnableMotor");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_EnableMotor(struct b2JointId jointId, _Bool enableMotor);
     * }
     */
    public static void b2WheelJoint_EnableMotor(MemorySegment jointId, boolean enableMotor) {
        var mh$ = b2WheelJoint_EnableMotor$MH();
        try {
            mh$.invokeExact(jointId, enableMotor);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_IsMotorEnabled$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$1,"b2WheelJoint_IsMotorEnabled");
    }
    /**
     * {@snippet lang=c :
     * _Bool b2WheelJoint_IsMotorEnabled(struct b2JointId jointId);
     * }
     */
    public static boolean b2WheelJoint_IsMotorEnabled(MemorySegment jointId) {
        var mh$ = b2WheelJoint_IsMotorEnabled$MH();
        try {
            return (boolean)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_SetMotorSpeed$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$2,"b2WheelJoint_SetMotorSpeed");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_SetMotorSpeed(struct b2JointId jointId, float motorSpeed);
     * }
     */
    public static void b2WheelJoint_SetMotorSpeed(MemorySegment jointId, float motorSpeed) {
        var mh$ = b2WheelJoint_SetMotorSpeed$MH();
        try {
            mh$.invokeExact(jointId, motorSpeed);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetMotorSpeed$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$3,"b2WheelJoint_GetMotorSpeed");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetMotorSpeed(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetMotorSpeed(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetMotorSpeed$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_SetMaxMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$4,"b2WheelJoint_SetMaxMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * void b2WheelJoint_SetMaxMotorTorque(struct b2JointId jointId, float torque);
     * }
     */
    public static void b2WheelJoint_SetMaxMotorTorque(MemorySegment jointId, float torque) {
        var mh$ = b2WheelJoint_SetMaxMotorTorque$MH();
        try {
            mh$.invokeExact(jointId, torque);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetMaxMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$226.const$5,"b2WheelJoint_GetMaxMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetMaxMotorTorque(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetMaxMotorTorque(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetMaxMotorTorque$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MethodHandle b2WheelJoint_GetMotorTorque$MH() {
        return RuntimeHelper.requireNonNull(constants$227.const$0,"b2WheelJoint_GetMotorTorque");
    }
    /**
     * {@snippet lang=c :
     * float b2WheelJoint_GetMotorTorque(struct b2JointId jointId);
     * }
     */
    public static float b2WheelJoint_GetMotorTorque(MemorySegment jointId) {
        var mh$ = b2WheelJoint_GetMotorTorque$MH();
        try {
            return (float)mh$.invokeExact(jointId);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    /**
     * {@snippet lang=c :
     * #define _VCRUNTIME_DISABLED_WARNINGS 4514
     * }
     */
    public static int _VCRUNTIME_DISABLED_WARNINGS() {
        return (int)4514L;
    }
    /**
     * {@snippet lang=c :
     * #define NULL 0
     * }
     */
    public static MemorySegment NULL() {
        return constants$227.const$1;
    }
    /**
     * {@snippet lang=c :
     * #define INT8_MIN -128
     * }
     */
    public static int INT8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet lang=c :
     * #define INT16_MIN -32768
     * }
     */
    public static int INT16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet lang=c :
     * #define INT32_MIN -2147483648
     * }
     */
    public static int INT32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define INT64_MIN -9223372036854775808
     * }
     */
    public static long INT64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define INT8_MAX 127
     * }
     */
    public static byte INT8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet lang=c :
     * #define INT16_MAX 32767
     * }
     */
    public static short INT16_MAX() {
        return (short)32767L;
    }
    /**
     * {@snippet lang=c :
     * #define INT32_MAX 2147483647
     * }
     */
    public static int INT32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet lang=c :
     * #define INT64_MAX 9223372036854775807
     * }
     */
    public static long INT64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT8_MAX 255
     * }
     */
    public static byte UINT8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT16_MAX 65535
     * }
     */
    public static short UINT16_MAX() {
        return (short)65535L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT32_MAX 4294967295
     * }
     */
    public static int UINT32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT64_MAX -1
     * }
     */
    public static long UINT64_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MIN -128
     * }
     */
    public static int INT_LEAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MIN -32768
     * }
     */
    public static int INT_LEAST16_MIN() {
        return (int)-32768L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MIN -2147483648
     * }
     */
    public static int INT_LEAST32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_LEAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST8_MAX 127
     * }
     */
    public static byte INT_LEAST8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST16_MAX 32767
     * }
     */
    public static short INT_LEAST16_MAX() {
        return (short)32767L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST32_MAX 2147483647
     * }
     */
    public static int INT_LEAST32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_LEAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_LEAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST8_MAX 255
     * }
     */
    public static byte UINT_LEAST8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST16_MAX 65535
     * }
     */
    public static short UINT_LEAST16_MAX() {
        return (short)65535L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST32_MAX 4294967295
     * }
     */
    public static int UINT_LEAST32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_LEAST64_MAX -1
     * }
     */
    public static long UINT_LEAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MIN -128
     * }
     */
    public static int INT_FAST8_MIN() {
        return (int)-128L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MIN -2147483648
     * }
     */
    public static int INT_FAST16_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MIN -2147483648
     * }
     */
    public static int INT_FAST32_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MIN -9223372036854775808
     * }
     */
    public static long INT_FAST64_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST8_MAX 127
     * }
     */
    public static byte INT_FAST8_MAX() {
        return (byte)127L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST16_MAX 2147483647
     * }
     */
    public static int INT_FAST16_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST32_MAX 2147483647
     * }
     */
    public static int INT_FAST32_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet lang=c :
     * #define INT_FAST64_MAX 9223372036854775807
     * }
     */
    public static long INT_FAST64_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_FAST8_MAX 255
     * }
     */
    public static byte UINT_FAST8_MAX() {
        return (byte)255L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_FAST16_MAX 4294967295
     * }
     */
    public static int UINT_FAST16_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_FAST32_MAX 4294967295
     * }
     */
    public static int UINT_FAST32_MAX() {
        return (int)4294967295L;
    }
    /**
     * {@snippet lang=c :
     * #define UINT_FAST64_MAX -1
     * }
     */
    public static long UINT_FAST64_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define INTPTR_MIN -9223372036854775808
     * }
     */
    public static long INTPTR_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define INTPTR_MAX 9223372036854775807
     * }
     */
    public static long INTPTR_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define UINTPTR_MAX -1
     * }
     */
    public static long UINTPTR_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define INTMAX_MIN -9223372036854775808
     * }
     */
    public static long INTMAX_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define INTMAX_MAX 9223372036854775807
     * }
     */
    public static long INTMAX_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define UINTMAX_MAX -1
     * }
     */
    public static long UINTMAX_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MIN -9223372036854775808
     * }
     */
    public static long PTRDIFF_MIN() {
        return -9223372036854775808L;
    }
    /**
     * {@snippet lang=c :
     * #define PTRDIFF_MAX 9223372036854775807
     * }
     */
    public static long PTRDIFF_MAX() {
        return 9223372036854775807L;
    }
    /**
     * {@snippet lang=c :
     * #define SIZE_MAX -1
     * }
     */
    public static long SIZE_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MIN -2147483648
     * }
     */
    public static int SIG_ATOMIC_MIN() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define SIG_ATOMIC_MAX 2147483647
     * }
     */
    public static int SIG_ATOMIC_MAX() {
        return (int)2147483647L;
    }
    /**
     * {@snippet lang=c :
     * #define _UCRT_DISABLED_WARNINGS 4324
     * }
     */
    public static int _UCRT_DISABLED_WARNINGS() {
        return (int)4324L;
    }
    /**
     * {@snippet lang=c :
     * #define _TRUNCATE -1
     * }
     */
    public static long _TRUNCATE() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define _CRT_SIZE_MAX -1
     * }
     */
    public static long _CRT_SIZE_MAX() {
        return -1L;
    }
    /**
     * {@snippet lang=c :
     * #define __FILEW__ "C"
     * }
     */
    public static MemorySegment __FILEW__() {
        return constants$227.const$2;
    }
    /**
     * {@snippet lang=c :
     * #define __STDC_SECURE_LIB__ 200411
     * }
     */
    public static int __STDC_SECURE_LIB__() {
        return (int)200411L;
    }
    /**
     * {@snippet lang=c :
     * #define __GOT_SECURE_LIB__ 200411
     * }
     */
    public static int __GOT_SECURE_LIB__() {
        return (int)200411L;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_EPSILON 2.220446049250313E-16
     * }
     */
    public static double DBL_EPSILON() {
        return 2.220446049250313E-16d;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_MAX 1.7976931348623157E308
     * }
     */
    public static double DBL_MAX() {
        return 1.7976931348623157E308d;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_MIN 2.2250738585072014E-308
     * }
     */
    public static double DBL_MIN() {
        return 2.2250738585072014E-308d;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_MIN_10_EXP -307
     * }
     */
    public static int DBL_MIN_10_EXP() {
        return (int)-307L;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_MIN_EXP -1021
     * }
     */
    public static int DBL_MIN_EXP() {
        return (int)-1021L;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_TRUE_MIN 4.9E-324
     * }
     */
    public static double DBL_TRUE_MIN() {
        return 4.9E-324d;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_EPSILON 1.1920928955078125E-7
     * }
     */
    public static float FLT_EPSILON() {
        return 1.1920928955078125E-7f;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_MAX 3.4028234663852886E38
     * }
     */
    public static float FLT_MAX() {
        return 3.4028234663852886E38f;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_MIN 1.1754943508222875E-38
     * }
     */
    public static float FLT_MIN() {
        return 1.1754943508222875E-38f;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_MIN_10_EXP -37
     * }
     */
    public static int FLT_MIN_10_EXP() {
        return (int)-37L;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_MIN_EXP -125
     * }
     */
    public static int FLT_MIN_EXP() {
        return (int)-125L;
    }
    /**
     * {@snippet lang=c :
     * #define FLT_TRUE_MIN 1.401298464324817E-45
     * }
     */
    public static float FLT_TRUE_MIN() {
        return 1.401298464324817E-45f;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_DIG 15
     * }
     */
    public static int LDBL_DIG() {
        return (int)15L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_EPSILON 2.220446049250313E-16
     * }
     */
    public static double LDBL_EPSILON() {
        return 2.220446049250313E-16d;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_HAS_SUBNORM 1
     * }
     */
    public static int LDBL_HAS_SUBNORM() {
        return (int)1L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MANT_DIG 53
     * }
     */
    public static int LDBL_MANT_DIG() {
        return (int)53L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MAX 1.7976931348623157E308
     * }
     */
    public static double LDBL_MAX() {
        return 1.7976931348623157E308d;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MAX_10_EXP 308
     * }
     */
    public static int LDBL_MAX_10_EXP() {
        return (int)308L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MAX_EXP 1024
     * }
     */
    public static int LDBL_MAX_EXP() {
        return (int)1024L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MIN 2.2250738585072014E-308
     * }
     */
    public static double LDBL_MIN() {
        return 2.2250738585072014E-308d;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MIN_10_EXP -307
     * }
     */
    public static int LDBL_MIN_10_EXP() {
        return (int)-307L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_MIN_EXP -1021
     * }
     */
    public static int LDBL_MIN_EXP() {
        return (int)-1021L;
    }
    /**
     * {@snippet lang=c :
     * #define _LDBL_RADIX 2
     * }
     */
    public static int _LDBL_RADIX() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_TRUE_MIN 4.9E-324
     * }
     */
    public static double LDBL_TRUE_MIN() {
        return 4.9E-324d;
    }
    /**
     * {@snippet lang=c :
     * #define DECIMAL_DIG 17
     * }
     */
    public static int DECIMAL_DIG() {
        return (int)17L;
    }
    /**
     * {@snippet lang=c :
     * #define _EM_AMBIGUIOUS 2147483648
     * }
     */
    public static int _EM_AMBIGUIOUS() {
        return (int)2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define _EM_AMBIGUOUS 2147483648
     * }
     */
    public static int _EM_AMBIGUOUS() {
        return (int)2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define _CW_DEFAULT 524319
     * }
     */
    public static int _CW_DEFAULT() {
        return (int)524319L;
    }
    /**
     * {@snippet lang=c :
     * #define DBL_RADIX 2
     * }
     */
    public static int DBL_RADIX() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_RADIX 2
     * }
     */
    public static int LDBL_RADIX() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_AMBIGUIOUS 2147483648
     * }
     */
    public static int EM_AMBIGUIOUS() {
        return (int)2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_AMBIGUOUS 2147483648
     * }
     */
    public static int EM_AMBIGUOUS() {
        return (int)2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define MCW_EM 524319
     * }
     */
    public static int MCW_EM() {
        return (int)524319L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_INVALID 16
     * }
     */
    public static int EM_INVALID() {
        return (int)16L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_DENORMAL 524288
     * }
     */
    public static int EM_DENORMAL() {
        return (int)524288L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_ZERODIVIDE 8
     * }
     */
    public static int EM_ZERODIVIDE() {
        return (int)8L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_OVERFLOW 4
     * }
     */
    public static int EM_OVERFLOW() {
        return (int)4L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_UNDERFLOW 2
     * }
     */
    public static int EM_UNDERFLOW() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define EM_INEXACT 1
     * }
     */
    public static int EM_INEXACT() {
        return (int)1L;
    }
    /**
     * {@snippet lang=c :
     * #define MCW_IC 262144
     * }
     */
    public static int MCW_IC() {
        return (int)262144L;
    }
    /**
     * {@snippet lang=c :
     * #define IC_AFFINE 262144
     * }
     */
    public static int IC_AFFINE() {
        return (int)262144L;
    }
    /**
     * {@snippet lang=c :
     * #define IC_PROJECTIVE 0
     * }
     */
    public static int IC_PROJECTIVE() {
        return (int)0L;
    }
    /**
     * {@snippet lang=c :
     * #define MCW_RC 768
     * }
     */
    public static int MCW_RC() {
        return (int)768L;
    }
    /**
     * {@snippet lang=c :
     * #define RC_CHOP 768
     * }
     */
    public static int RC_CHOP() {
        return (int)768L;
    }
    /**
     * {@snippet lang=c :
     * #define RC_UP 512
     * }
     */
    public static int RC_UP() {
        return (int)512L;
    }
    /**
     * {@snippet lang=c :
     * #define RC_DOWN 256
     * }
     */
    public static int RC_DOWN() {
        return (int)256L;
    }
    /**
     * {@snippet lang=c :
     * #define RC_NEAR 0
     * }
     */
    public static int RC_NEAR() {
        return (int)0L;
    }
    /**
     * {@snippet lang=c :
     * #define MCW_PC 196608
     * }
     */
    public static int MCW_PC() {
        return (int)196608L;
    }
    /**
     * {@snippet lang=c :
     * #define PC_24 131072
     * }
     */
    public static int PC_24() {
        return (int)131072L;
    }
    /**
     * {@snippet lang=c :
     * #define PC_53 65536
     * }
     */
    public static int PC_53() {
        return (int)65536L;
    }
    /**
     * {@snippet lang=c :
     * #define PC_64 0
     * }
     */
    public static int PC_64() {
        return (int)0L;
    }
    /**
     * {@snippet lang=c :
     * #define CW_DEFAULT 524319
     * }
     */
    public static int CW_DEFAULT() {
        return (int)524319L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_INVALID 16
     * }
     */
    public static int SW_INVALID() {
        return (int)16L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_DENORMAL 524288
     * }
     */
    public static int SW_DENORMAL() {
        return (int)524288L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_ZERODIVIDE 8
     * }
     */
    public static int SW_ZERODIVIDE() {
        return (int)8L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_OVERFLOW 4
     * }
     */
    public static int SW_OVERFLOW() {
        return (int)4L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_UNDERFLOW 2
     * }
     */
    public static int SW_UNDERFLOW() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_INEXACT 1
     * }
     */
    public static int SW_INEXACT() {
        return (int)1L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_UNEMULATED 64
     * }
     */
    public static int SW_UNEMULATED() {
        return (int)64L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_SQRTNEG 128
     * }
     */
    public static int SW_SQRTNEG() {
        return (int)128L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_STACKOVERFLOW 512
     * }
     */
    public static int SW_STACKOVERFLOW() {
        return (int)512L;
    }
    /**
     * {@snippet lang=c :
     * #define SW_STACKUNDERFLOW 1024
     * }
     */
    public static int SW_STACKUNDERFLOW() {
        return (int)1024L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_INVALID 129
     * }
     */
    public static int FPE_INVALID() {
        return (int)129L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_DENORMAL 130
     * }
     */
    public static int FPE_DENORMAL() {
        return (int)130L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_ZERODIVIDE 131
     * }
     */
    public static int FPE_ZERODIVIDE() {
        return (int)131L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_OVERFLOW 132
     * }
     */
    public static int FPE_OVERFLOW() {
        return (int)132L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_UNDERFLOW 133
     * }
     */
    public static int FPE_UNDERFLOW() {
        return (int)133L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_INEXACT 134
     * }
     */
    public static int FPE_INEXACT() {
        return (int)134L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_UNEMULATED 135
     * }
     */
    public static int FPE_UNEMULATED() {
        return (int)135L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_SQRTNEG 136
     * }
     */
    public static int FPE_SQRTNEG() {
        return (int)136L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_STACKOVERFLOW 138
     * }
     */
    public static int FPE_STACKOVERFLOW() {
        return (int)138L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_STACKUNDERFLOW 139
     * }
     */
    public static int FPE_STACKUNDERFLOW() {
        return (int)139L;
    }
    /**
     * {@snippet lang=c :
     * #define FPE_EXPLICITGEN 140
     * }
     */
    public static int FPE_EXPLICITGEN() {
        return (int)140L;
    }
    /**
     * {@snippet lang=c :
     * #define LDBL_DECIMAL_DIG 17
     * }
     */
    public static int LDBL_DECIMAL_DIG() {
        return (int)17L;
    }
    /**
     * {@snippet lang=c :
     * #define _HUGE_ENUF 1.0E300
     * }
     */
    public static double _HUGE_ENUF() {
        return 1.0E300d;
    }
    /**
     * {@snippet lang=c :
     * #define INFINITY Infinity
     * }
     */
    public static float INFINITY() {
        return Float.valueOf("Infinity");
    }
    /**
     * {@snippet lang=c :
     * #define HUGE_VAL Infinity
     * }
     */
    public static double HUGE_VAL() {
        return Double.valueOf("Infinity");
    }
    /**
     * {@snippet lang=c :
     * #define HUGE_VALF Infinity
     * }
     */
    public static float HUGE_VALF() {
        return Float.valueOf("Infinity");
    }
    /**
     * {@snippet lang=c :
     * #define HUGE_VALL Infinity
     * }
     */
    public static double HUGE_VALL() {
        return Double.valueOf("Infinity");
    }
    /**
     * {@snippet lang=c :
     * #define _UCRT_NAN NaN
     * }
     */
    public static float _UCRT_NAN() {
        return Float.valueOf("NaN");
    }
    /**
     * {@snippet lang=c :
     * #define NAN NaN
     * }
     */
    public static float NAN() {
        return Float.valueOf("NaN");
    }
    /**
     * {@snippet lang=c :
     * #define _DENORM -2
     * }
     */
    public static int _DENORM() {
        return (int)-2L;
    }
    /**
     * {@snippet lang=c :
     * #define _FINITE -1
     * }
     */
    public static int _FINITE() {
        return (int)-1L;
    }
    /**
     * {@snippet lang=c :
     * #define FP_INFINITE 1
     * }
     */
    public static int FP_INFINITE() {
        return (int)1L;
    }
    /**
     * {@snippet lang=c :
     * #define FP_NAN 2
     * }
     */
    public static int FP_NAN() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define FP_NORMAL -1
     * }
     */
    public static int FP_NORMAL() {
        return (int)-1L;
    }
    /**
     * {@snippet lang=c :
     * #define FP_SUBNORMAL -2
     * }
     */
    public static int FP_SUBNORMAL() {
        return (int)-2L;
    }
    /**
     * {@snippet lang=c :
     * #define FP_ILOGB0 -2147483648
     * }
     */
    public static int FP_ILOGB0() {
        return (int)-2147483648L;
    }
    /**
     * {@snippet lang=c :
     * #define math_errhandling 3
     * }
     */
    public static int math_errhandling() {
        return (int)3L;
    }
    /**
     * {@snippet lang=c :
     * #define _DFRAC 15
     * }
     */
    public static short _DFRAC() {
        return (short)15L;
    }
    /**
     * {@snippet lang=c :
     * #define _DMASK 32752
     * }
     */
    public static short _DMASK() {
        return (short)32752L;
    }
    /**
     * {@snippet lang=c :
     * #define _DMAX 2047
     * }
     */
    public static short _DMAX() {
        return (short)2047L;
    }
    /**
     * {@snippet lang=c :
     * #define _DSIGN 32768
     * }
     */
    public static short _DSIGN() {
        return (short)32768L;
    }
    /**
     * {@snippet lang=c :
     * #define _FFRAC 127
     * }
     */
    public static short _FFRAC() {
        return (short)127L;
    }
    /**
     * {@snippet lang=c :
     * #define _FMASK 32640
     * }
     */
    public static short _FMASK() {
        return (short)32640L;
    }
    /**
     * {@snippet lang=c :
     * #define _FMAX 255
     * }
     */
    public static short _FMAX() {
        return (short)255L;
    }
    /**
     * {@snippet lang=c :
     * #define _FSIGN 32768
     * }
     */
    public static short _FSIGN() {
        return (short)32768L;
    }
    /**
     * {@snippet lang=c :
     * #define _LFRAC 65535
     * }
     */
    public static short _LFRAC() {
        return (short)65535L;
    }
    /**
     * {@snippet lang=c :
     * #define _LMASK 32767
     * }
     */
    public static short _LMASK() {
        return (short)32767L;
    }
    /**
     * {@snippet lang=c :
     * #define _LMAX 32767
     * }
     */
    public static short _LMAX() {
        return (short)32767L;
    }
    /**
     * {@snippet lang=c :
     * #define _LSIGN 32768
     * }
     */
    public static short _LSIGN() {
        return (short)32768L;
    }
    /**
     * {@snippet lang=c :
     * #define _DHUGE_EXP 1842
     * }
     */
    public static int _DHUGE_EXP() {
        return (int)1842L;
    }
    /**
     * {@snippet lang=c :
     * #define _FHUGE_EXP 229
     * }
     */
    public static int _FHUGE_EXP() {
        return (int)229L;
    }
    /**
     * {@snippet lang=c :
     * #define _LHUGE_EXP 29490
     * }
     */
    public static int _LHUGE_EXP() {
        return (int)29490L;
    }
    /**
     * {@snippet lang=c :
     * #define DOMAIN 1
     * }
     */
    public static int DOMAIN() {
        return (int)1L;
    }
    /**
     * {@snippet lang=c :
     * #define SING 2
     * }
     */
    public static int SING() {
        return (int)2L;
    }
    /**
     * {@snippet lang=c :
     * #define OVERFLOW 3
     * }
     */
    public static int OVERFLOW() {
        return (int)3L;
    }
    /**
     * {@snippet lang=c :
     * #define UNDERFLOW 4
     * }
     */
    public static int UNDERFLOW() {
        return (int)4L;
    }
    /**
     * {@snippet lang=c :
     * #define TLOSS 5
     * }
     */
    public static int TLOSS() {
        return (int)5L;
    }
    /**
     * {@snippet lang=c :
     * #define PLOSS 6
     * }
     */
    public static int PLOSS() {
        return (int)6L;
    }
    /**
     * {@snippet lang=c :
     * #define B2_PI 3.1415927410125732
     * }
     */
    public static float B2_PI() {
        return 3.1415927410125732f;
    }
    /**
     * {@snippet lang=c :
     * #define B2_DEFAULT_MASK_BITS -1
     * }
     */
    public static long B2_DEFAULT_MASK_BITS() {
        return -1L;
    }
}


