// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2SetAssertFcn",
        constants$0.const$0
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("major"),
        JAVA_INT.withName("minor"),
        JAVA_INT.withName("revision")
    ).withName("b2Version");
    static final VarHandle const$2 = constants$4.const$1.varHandle(MemoryLayout.PathElement.groupElement("major"));
    static final VarHandle const$3 = constants$4.const$1.varHandle(MemoryLayout.PathElement.groupElement("minor"));
    static final VarHandle const$4 = constants$4.const$1.varHandle(MemoryLayout.PathElement.groupElement("revision"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("major"),
        JAVA_INT.withName("minor"),
        JAVA_INT.withName("revision")
    ).withName("b2Version"));
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2GetVersion",
        constants$4.const$5
    );
}


