// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("b2Vec2")).withName("points"),
            JAVA_INT.withName("count"),
            JAVA_FLOAT.withName("radius")
        ).withName("proxyA"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("b2Vec2")).withName("points"),
            JAVA_INT.withName("count"),
            JAVA_FLOAT.withName("radius")
        ).withName("proxyB"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("localCenter"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("c1"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("c2"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("c"),
                JAVA_FLOAT.withName("s")
            ).withName("q1"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("c"),
                JAVA_FLOAT.withName("s")
            ).withName("q2")
        ).withName("sweepA"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("localCenter"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("c1"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("c2"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("c"),
                JAVA_FLOAT.withName("s")
            ).withName("q1"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("c"),
                JAVA_FLOAT.withName("s")
            ).withName("q2")
        ).withName("sweepB"),
        JAVA_FLOAT.withName("maxFraction")
    ).withName("b2TOIInput");
    static final VarHandle const$1 = constants$83.const$0.varHandle(MemoryLayout.PathElement.groupElement("maxFraction"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("state"),
        JAVA_FLOAT.withName("fraction")
    ).withName("b2TOIOutput");
    static final VarHandle const$3 = constants$83.const$2.varHandle(MemoryLayout.PathElement.groupElement("state"));
    static final VarHandle const$4 = constants$83.const$2.varHandle(MemoryLayout.PathElement.groupElement("fraction"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("state"),
        JAVA_FLOAT.withName("fraction")
    ).withName("b2TOIOutput"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2TimeOfImpact",
        constants$83.const$5
    );
}


