// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$150 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$150() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(b2DebugDraw.DrawPolygonFcn.class, "apply", constants$149.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$149.const$5
    );
    static final VarHandle const$2 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("DrawPolygonFcn"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("p"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("c"),
                JAVA_FLOAT.withName("s")
            ).withName("q")
        ).withName("b2Transform"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_FLOAT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(b2DebugDraw.DrawSolidPolygonFcn.class, "apply", constants$150.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$150.const$3
    );
}


