// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$118 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$118() {}
    static final VarHandle const$0 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("count"));
    static final VarHandle const$1 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("materials"));
    static final VarHandle const$2 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("materialCount"));
    static final VarHandle const$3 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("isLoop"));
    static final VarHandle const$4 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("enableSensorEvents"));
    static final VarHandle const$5 = constants$117.const$3.varHandle(MemoryLayout.PathElement.groupElement("internalValue"));
}


