// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final VarHandle const$0 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("maxForce"));
    static final VarHandle const$1 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("maxTorque"));
    static final VarHandle const$2 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("correctionFactor"));
    static final VarHandle const$3 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("collideConnected"));
    static final VarHandle const$4 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("userData"));
    static final VarHandle const$5 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("internalValue"));
}


