// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$215 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$215() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2CreatePrismaticJoint",
        constants$207.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2PrismaticJoint_EnableSpring",
        constants$205.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2PrismaticJoint_IsSpringEnabled",
        constants$202.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2PrismaticJoint_SetSpringHertz",
        constants$204.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2PrismaticJoint_GetSpringHertz",
        constants$204.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2PrismaticJoint_SetSpringDampingRatio",
        constants$204.const$4
    );
}


