// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$109 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$109() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("position"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("rotation"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("linearVelocity"),
        JAVA_FLOAT.withName("angularVelocity"),
        JAVA_FLOAT.withName("linearDamping"),
        JAVA_FLOAT.withName("angularDamping"),
        JAVA_FLOAT.withName("gravityScale"),
        JAVA_FLOAT.withName("sleepThreshold"),
        RuntimeHelper.POINTER.withName("name"),
        RuntimeHelper.POINTER.withName("userData"),
        JAVA_BOOLEAN.withName("enableSleep"),
        JAVA_BOOLEAN.withName("isAwake"),
        JAVA_BOOLEAN.withName("fixedRotation"),
        JAVA_BOOLEAN.withName("isBullet"),
        JAVA_BOOLEAN.withName("isEnabled"),
        JAVA_BOOLEAN.withName("allowFastRotation"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("internalValue"),
        MemoryLayout.paddingLayout(4)
    ).withName("b2BodyDef");
    static final VarHandle const$1 = constants$109.const$0.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$2 = constants$109.const$0.varHandle(MemoryLayout.PathElement.groupElement("angularVelocity"));
    static final VarHandle const$3 = constants$109.const$0.varHandle(MemoryLayout.PathElement.groupElement("linearDamping"));
    static final VarHandle const$4 = constants$109.const$0.varHandle(MemoryLayout.PathElement.groupElement("angularDamping"));
    static final VarHandle const$5 = constants$109.const$0.varHandle(MemoryLayout.PathElement.groupElement("gravityScale"));
}


