// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "exp2l",
        constants$11.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "expm1l",
        constants$11.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "fdiml",
        constants$11.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "fmal",
        constants$35.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "fmaxl",
        constants$11.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "fminl",
        constants$11.const$0
    );
}


