// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$212 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$212() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_SetAngularOffset",
        constants$204.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_GetAngularOffset",
        constants$204.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_SetMaxForce",
        constants$204.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_GetMaxForce",
        constants$204.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_SetMaxTorque",
        constants$204.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2MotorJoint_GetMaxTorque",
        constants$204.const$2
    );
}


