// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$203 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$203() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2Joint_GetBodyB",
        constants$202.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_SHORT.withName("index1"),
        JAVA_SHORT.withName("generation")
    ).withName("b2WorldId"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2JointId")
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2Joint_GetWorld",
        constants$203.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2JointId"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2Joint_SetLocalAnchorA",
        constants$203.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_FLOAT.withName("x"),
        JAVA_FLOAT.withName("y")
    ).withName("b2Vec2"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2JointId")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2Joint_GetLocalAnchorA",
        constants$203.const$5
    );
}


