// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$148 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$148() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$147.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(b2OverlapResultFcn.class, "apply", constants$148.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$148.const$1
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2"),
        JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(b2CastResultFcn.class, "apply", constants$148.const$4);
}


