// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$114 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$114() {}
    static final VarHandle const$0 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("friction"));
    static final VarHandle const$1 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("restitution"));
    static final VarHandle const$2 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("rollingResistance"));
    static final VarHandle const$3 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("tangentSpeed"));
    static final VarHandle const$4 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("userMaterialId"));
    static final VarHandle const$5 = constants$113.const$5.varHandle(MemoryLayout.PathElement.groupElement("customColor"));
}


