// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    static final UnionLayout const$0 = MemoryLayout.unionLayout(
        MemoryLayout.sequenceLayout(4, JAVA_SHORT).withName("_Word"),
        JAVA_FLOAT.withName("_Float"),
        JAVA_DOUBLE.withName("_Double"),
        JAVA_DOUBLE.withName("_Long_double")
    ).withName("_float_const");
    static final VarHandle const$1 = constants$24.const$0.varHandle(MemoryLayout.PathElement.groupElement("_Float"));
    static final VarHandle const$2 = constants$24.const$0.varHandle(MemoryLayout.PathElement.groupElement("_Double"));
    static final VarHandle const$3 = constants$24.const$0.varHandle(MemoryLayout.PathElement.groupElement("_Long_double"));
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("_Denorm_C", constants$24.const$0);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("_Inf_C", constants$24.const$0);
}


