// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$116 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$116() {}
    static final VarHandle const$0 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("enableSensorEvents"));
    static final VarHandle const$1 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("enableContactEvents"));
    static final VarHandle const$2 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("enableHitEvents"));
    static final VarHandle const$3 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("enablePreSolveEvents"));
    static final VarHandle const$4 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("invokeContactCreation"));
    static final VarHandle const$5 = constants$115.const$2.varHandle(MemoryLayout.PathElement.groupElement("updateBodyMass"));
}


