// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = JAVA_DOUBLE.varHandle();
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("_HUGE", JAVA_DOUBLE);
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid(
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "_fperrraise",
        constants$15.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_SHORT,
        JAVA_DOUBLE
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "_dclass",
        constants$15.const$4
    );
}


