// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$33 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$33() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "atanh",
        constants$11.const$2
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_DOUBLE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "atof",
        constants$33.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_atof_l",
        constants$33.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_DOUBLE,
        MemoryLayout.structLayout(
            JAVA_DOUBLE.withName("x"),
            JAVA_DOUBLE.withName("y")
        ).withName("_complex")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "_cabs",
        constants$33.const$5
    );
}


