// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "sinf",
        constants$42.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "sinhf",
        constants$42.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "sqrtf",
        constants$42.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "tanf",
        constants$42.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "tanhf",
        constants$42.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "acoshl",
        constants$11.const$2
    );
}


