// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$45 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$45() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmaxf",
        constants$43.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "fminf",
        constants$43.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_hypotf",
        constants$43.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$16.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lgammaf",
        constants$42.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_LONG,
        JAVA_FLOAT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "llrintf",
        constants$45.const$5
    );
}


