// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "_dnorm",
        constants$17.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_fdnorm",
        constants$17.const$5
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "_dpoly",
        constants$21.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_ldpoly",
        constants$21.const$2
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "_fdpoly",
        constants$21.const$5
    );
}


