// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$200 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$200() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ChainId"),
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2Chain_SetFriction",
        constants$200.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ChainId")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2Chain_GetFriction",
        constants$200.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2Chain_SetRestitution",
        constants$200.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2Chain_GetRestitution",
        constants$200.const$2
    );
}


