// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    static final VarHandle const$0 = constants$69.const$5.varHandle(MemoryLayout.PathElement.groupElement("chainId"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_BOOLEAN,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2IsValidRay",
        constants$70.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("vertices"),
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("normals"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("centroid"),
        JAVA_FLOAT.withName("radius"),
        JAVA_INT.withName("count")
    ).withName("b2Polygon"),
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2MakePolygon",
        constants$70.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("vertices"),
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("normals"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("centroid"),
        JAVA_FLOAT.withName("radius"),
        JAVA_INT.withName("count")
    ).withName("b2Polygon"),
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("b2Rot")
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2MakeOffsetPolygon",
        constants$70.const$5
    );
}


