// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$226 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$226() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_EnableMotor",
        constants$205.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_IsMotorEnabled",
        constants$202.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_SetMotorSpeed",
        constants$204.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_GetMotorSpeed",
        constants$204.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_SetMaxMotorTorque",
        constants$204.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2WheelJoint_GetMaxMotorTorque",
        constants$204.const$2
    );
}


