// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$187 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$187() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2Shape_GetType",
        constants$187.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("index1"),
        JAVA_SHORT.withName("world0"),
        JAVA_SHORT.withName("generation")
    ).withName("b2BodyId"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2Shape_GetBody",
        constants$187.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_SHORT.withName("index1"),
        JAVA_SHORT.withName("generation")
    ).withName("b2WorldId"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2Shape_GetWorld",
        constants$187.const$4
    );
}


