// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$52 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$52() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmodf",
        constants$43.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "log10f",
        constants$42.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "logf",
        constants$42.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "modff",
        constants$52.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "powf",
        constants$43.const$3
    );
}


