// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$120 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$120() {}
    static final VarHandle const$0 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("solve"));
    static final VarHandle const$1 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("mergeIslands"));
    static final VarHandle const$2 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("prepareStages"));
    static final VarHandle const$3 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("solveConstraints"));
    static final VarHandle const$4 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("prepareConstraints"));
    static final VarHandle const$5 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("integrateVelocities"));
}


