// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$68 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$68() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("mass"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("center"),
        JAVA_FLOAT.withName("rotationalInertia")
    ).withName("b2MassData");
    static final VarHandle const$1 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("mass"));
    static final VarHandle const$2 = constants$68.const$0.varHandle(MemoryLayout.PathElement.groupElement("rotationalInertia"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("center"),
        JAVA_FLOAT.withName("radius")
    ).withName("b2Circle");
    static final VarHandle const$4 = constants$68.const$3.varHandle(MemoryLayout.PathElement.groupElement("radius"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("center1"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("center2"),
        JAVA_FLOAT.withName("radius")
    ).withName("b2Capsule");
}


