// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MemorySegment const$0 = RuntimeHelper.lookupGlobalVariable("_FSnan_C", constants$24.const$0);
    static final MemorySegment const$1 = RuntimeHelper.lookupGlobalVariable("_LDenorm_C", constants$24.const$0);
    static final MemorySegment const$2 = RuntimeHelper.lookupGlobalVariable("_LInf_C", constants$24.const$0);
    static final MemorySegment const$3 = RuntimeHelper.lookupGlobalVariable("_LNan_C", constants$24.const$0);
    static final MemorySegment const$4 = RuntimeHelper.lookupGlobalVariable("_LSnan_C", constants$24.const$0);
    static final MemorySegment const$5 = RuntimeHelper.lookupGlobalVariable("_Eps_C", constants$24.const$0);
}


