// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$171 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$171() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2BodyId")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2DestroyBody",
        constants$171.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2BodyId")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2Body_IsValid",
        constants$171.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_INT,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2BodyId")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2Body_GetType",
        constants$171.const$4
    );
}


