// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$193 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$193() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2Shape_EnableHitEvents",
        constants$186.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2Shape_AreHitEventsEnabled",
        constants$186.const$4
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_BOOLEAN,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2Shape_TestPoint",
        constants$193.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("normal"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("point"),
        JAVA_FLOAT.withName("fraction"),
        JAVA_INT.withName("iterations"),
        JAVA_BOOLEAN.withName("hit"),
        MemoryLayout.paddingLayout(3)
    ).withName("b2CastOutput"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2Shape_RayCast",
        constants$193.const$4
    );
}


