// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$61 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$61() {}
    static final VarHandle const$0 = constants$60.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("cosine"),
        JAVA_FLOAT.withName("sine")
    ).withName("b2CosSin");
    static final VarHandle const$2 = constants$61.const$1.varHandle(MemoryLayout.PathElement.groupElement("cosine"));
    static final VarHandle const$3 = constants$61.const$1.varHandle(MemoryLayout.PathElement.groupElement("sine"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("c"),
        JAVA_FLOAT.withName("s")
    ).withName("b2Rot");
    static final VarHandle const$5 = constants$61.const$4.varHandle(MemoryLayout.PathElement.groupElement("c"));
}


