// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$132 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$132() {}
    static final VarHandle const$0 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("targetTranslation"));
    static final VarHandle const$1 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("enableSpring"));
    static final VarHandle const$2 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("hertz"));
    static final VarHandle const$3 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("dampingRatio"));
    static final VarHandle const$4 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("enableLimit"));
    static final VarHandle const$5 = constants$131.const$4.varHandle(MemoryLayout.PathElement.groupElement("lowerTranslation"));
}


