// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "asinhl",
        constants$11.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "atanhl",
        constants$11.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "cbrtl",
        constants$11.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "copysignl",
        constants$11.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "erfl",
        constants$11.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "erfcl",
        constants$11.const$2
    );
}


