// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$56 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$56() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "ilogbl",
        constants$12.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "lgammal",
        constants$11.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "llrintl",
        constants$37.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "llroundl",
        constants$37.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "log1pl",
        constants$11.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "log2l",
        constants$11.const$2
    );
}


