// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$36 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$36() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "fmin",
        constants$11.const$0
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "frexp",
        constants$36.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "hypot",
        constants$11.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "_hypot",
        constants$11.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "ilogb",
        constants$12.const$2
    );
}


