// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(b2WorldDef.finishTask.class, "apply", constants$3.const$1);
    static final VarHandle const$1 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("finishTask"));
    static final VarHandle const$2 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("userTaskContext"));
    static final VarHandle const$3 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("userData"));
    static final VarHandle const$4 = constants$105.const$2.varHandle(MemoryLayout.PathElement.groupElement("internalValue"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("gravity"),
        JAVA_FLOAT.withName("restitutionThreshold"),
        JAVA_FLOAT.withName("hitEventThreshold"),
        JAVA_FLOAT.withName("contactHertz"),
        JAVA_FLOAT.withName("contactDampingRatio"),
        JAVA_FLOAT.withName("maxContactPushSpeed"),
        JAVA_FLOAT.withName("maximumLinearSpeed"),
        RuntimeHelper.POINTER.withName("frictionCallback"),
        RuntimeHelper.POINTER.withName("restitutionCallback"),
        JAVA_BOOLEAN.withName("enableSleep"),
        JAVA_BOOLEAN.withName("enableContinuous"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("workerCount"),
        RuntimeHelper.POINTER.withName("enqueueTask"),
        RuntimeHelper.POINTER.withName("finishTask"),
        RuntimeHelper.POINTER.withName("userTaskContext"),
        RuntimeHelper.POINTER.withName("userData"),
        JAVA_INT.withName("internalValue"),
        MemoryLayout.paddingLayout(4)
    ).withName("b2WorldDef"));
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2DefaultWorldDef",
        constants$108.const$5
    );
}


