// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$160 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$160() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("moveEvents"),
        JAVA_INT.withName("moveCount"),
        MemoryLayout.paddingLayout(4)
    ).withName("b2BodyEvents"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId")
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2World_GetBodyEvents",
        constants$160.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("beginEvents"),
        RuntimeHelper.POINTER.withName("endEvents"),
        JAVA_INT.withName("beginCount"),
        JAVA_INT.withName("endCount")
    ).withName("b2SensorEvents"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2World_GetSensorEvents",
        constants$160.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("beginEvents"),
        RuntimeHelper.POINTER.withName("endEvents"),
        RuntimeHelper.POINTER.withName("hitEvents"),
        JAVA_INT.withName("beginCount"),
        JAVA_INT.withName("endCount"),
        JAVA_INT.withName("hitCount"),
        MemoryLayout.paddingLayout(4)
    ).withName("b2ContactEvents"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId")
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2World_GetContactEvents",
        constants$160.const$4
    );
}


