// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$188 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$188() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2Shape_IsSensor",
        constants$186.const$4
    );
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2Shape_SetUserData",
        constants$188.const$1
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId")
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2Shape_GetUserData",
        constants$188.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_INT.withName("index1"),
            JAVA_SHORT.withName("world0"),
            JAVA_SHORT.withName("generation")
        ).withName("b2ShapeId"),
        JAVA_FLOAT,
        JAVA_BOOLEAN
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2Shape_SetDensity",
        constants$188.const$5
    );
}


