// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "llroundf",
        constants$45.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "log1pf",
        constants$42.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "log2f",
        constants$42.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "logbf",
        constants$42.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "lrintf",
        constants$16.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "lroundf",
        constants$16.const$5
    );
}


