// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$182 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$182() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2Body_SetSleepThreshold",
        constants$176.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2Body_GetSleepThreshold",
        constants$175.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2Body_IsEnabled",
        constants$171.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2Body_Disable",
        constants$171.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2Body_Enable",
        constants$171.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2Body_SetFixedRotation",
        constants$181.const$2
    );
}


