// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "cbrt",
        constants$11.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "ceil",
        constants$11.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "copysign",
        constants$11.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "erf",
        constants$11.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "erfc",
        constants$11.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "exp2",
        constants$11.const$2
    );
}


