// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$10 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$10() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "_statusfp",
        constants$3.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "_fpreset",
        constants$0.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "_control87",
        constants$9.const$0
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(RuntimeHelper.POINTER);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "__fpecode",
        constants$10.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "__fpe_flt_rounds",
        constants$3.const$3
    );
}


