// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$88 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$88() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("nodes"),
        JAVA_INT.withName("root"),
        JAVA_INT.withName("nodeCount"),
        JAVA_INT.withName("nodeCapacity"),
        JAVA_INT.withName("freeList"),
        JAVA_INT.withName("proxyCount"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("leafIndices"),
        RuntimeHelper.POINTER.withName("leafBoxes"),
        RuntimeHelper.POINTER.withName("leafCenters"),
        RuntimeHelper.POINTER.withName("binIndices"),
        JAVA_INT.withName("rebuildCapacity"),
        MemoryLayout.paddingLayout(4)
    ).withName("b2DynamicTree");
    static final VarHandle const$1 = constants$88.const$0.varHandle(MemoryLayout.PathElement.groupElement("nodes"));
    static final VarHandle const$2 = constants$88.const$0.varHandle(MemoryLayout.PathElement.groupElement("root"));
    static final VarHandle const$3 = constants$88.const$0.varHandle(MemoryLayout.PathElement.groupElement("nodeCount"));
    static final VarHandle const$4 = constants$88.const$0.varHandle(MemoryLayout.PathElement.groupElement("nodeCapacity"));
    static final VarHandle const$5 = constants$88.const$0.varHandle(MemoryLayout.PathElement.groupElement("freeList"));
}


