// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$161 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$161() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(b2World_OverlapAABB$fcn.class, "apply", constants$148.const$1);
    static final FunctionDescriptor const$1 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("nodeVisits"),
        JAVA_INT.withName("leafVisits")
    ).withName("b2TreeStats"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId"),
        MemoryLayout.structLayout(
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("lowerBound"),
            MemoryLayout.structLayout(
                JAVA_FLOAT.withName("x"),
                JAVA_FLOAT.withName("y")
            ).withName("upperBound")
        ).withName("b2AABB"),
        MemoryLayout.structLayout(
            JAVA_LONG.withName("categoryBits"),
            JAVA_LONG.withName("maskBits")
        ).withName("b2QueryFilter"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2World_OverlapAABB",
        constants$161.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(b2World_OverlapShape$fcn.class, "apply", constants$148.const$1);
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("nodeVisits"),
        JAVA_INT.withName("leafVisits")
    ).withName("b2TreeStats"),
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId"),
        RuntimeHelper.POINTER,
        MemoryLayout.structLayout(
            JAVA_LONG.withName("categoryBits"),
            JAVA_LONG.withName("maskBits")
        ).withName("b2QueryFilter"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "b2World_OverlapShape",
        constants$161.const$4
    );
}


