// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$164 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$164() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId"),
        JAVA_BOOLEAN
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2World_EnableSleeping",
        constants$164.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2World_IsSleepingEnabled",
        constants$159.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2World_EnableContinuous",
        constants$164.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2World_IsContinuousEnabled",
        constants$159.const$0
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            JAVA_SHORT.withName("index1"),
            JAVA_SHORT.withName("generation")
        ).withName("b2WorldId"),
        JAVA_FLOAT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2World_SetRestitutionThreshold",
        constants$164.const$5
    );
}


