// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$156 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$156() {}
    static final VarHandle const$0 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawJointExtras"));
    static final VarHandle const$1 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawBounds"));
    static final VarHandle const$2 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawMass"));
    static final VarHandle const$3 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawBodyNames"));
    static final VarHandle const$4 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawContacts"));
    static final VarHandle const$5 = constants$149.const$4.varHandle(MemoryLayout.PathElement.groupElement("drawGraphColors"));
}


