// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$103 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$103() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(b2EnqueueTaskCallback.class, "apply", constants$103.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$103.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(b2FinishTaskCallback.class, "apply", constants$3.const$1);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$3.const$1
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_INT,
        JAVA_FLOAT,
        JAVA_INT
    );
}


