// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$76 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$76() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "b2RayCastPolygon",
        constants$75.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2ShapeCastCircle",
        constants$75.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "b2ShapeCastCapsule",
        constants$75.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2ShapeCastSegment",
        constants$75.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "b2ShapeCastPolygon",
        constants$75.const$2
    );
    static final StructLayout const$5 = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("points"),
        JAVA_INT.withName("count")
    ).withName("b2Hull");
}


