// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final VarHandle const$0 = constants$119.const$2.varHandle(MemoryLayout.PathElement.groupElement("sensors"));
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("bodyCount"),
        JAVA_INT.withName("shapeCount"),
        JAVA_INT.withName("contactCount"),
        JAVA_INT.withName("jointCount"),
        JAVA_INT.withName("islandCount"),
        JAVA_INT.withName("stackUsed"),
        JAVA_INT.withName("staticTreeHeight"),
        JAVA_INT.withName("treeHeight"),
        JAVA_INT.withName("byteCount"),
        JAVA_INT.withName("taskCount"),
        MemoryLayout.sequenceLayout(12, JAVA_INT).withName("colorCounts")
    ).withName("b2Counters");
    static final VarHandle const$2 = constants$123.const$1.varHandle(MemoryLayout.PathElement.groupElement("bodyCount"));
    static final VarHandle const$3 = constants$123.const$1.varHandle(MemoryLayout.PathElement.groupElement("shapeCount"));
    static final VarHandle const$4 = constants$123.const$1.varHandle(MemoryLayout.PathElement.groupElement("contactCount"));
    static final VarHandle const$5 = constants$123.const$1.varHandle(MemoryLayout.PathElement.groupElement("jointCount"));
}


