// Generated by jextract

package org.box2d;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("points"),
        JAVA_INT.withName("count"),
        JAVA_FLOAT.withName("radius")
    ).withName("b2ShapeProxy"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_FLOAT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "b2MakeProxy",
        constants$82.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2")).withName("points"),
        JAVA_INT.withName("count"),
        JAVA_FLOAT.withName("radius")
    ).withName("b2ShapeProxy"),
        RuntimeHelper.POINTER,
        JAVA_INT,
        JAVA_FLOAT,
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("b2Vec2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("b2Rot")
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "b2MakeOffsetProxy",
        constants$82.const$2
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("localCenter"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("c1"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("c2"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("q1"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("q2")
    ).withName("b2Sweep");
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("x"),
            JAVA_FLOAT.withName("y")
        ).withName("p"),
        MemoryLayout.structLayout(
            JAVA_FLOAT.withName("c"),
            JAVA_FLOAT.withName("s")
        ).withName("q")
    ).withName("b2Transform"),
        RuntimeHelper.POINTER,
        JAVA_FLOAT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "b2GetSweepTransform",
        constants$82.const$5
    );
}


