// Generated by jextract

package org.box2d.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef float (b2CastResultFcn)(b2ShapeId, b2Vec2, b2Vec2, float, void *)
 * }
 */
public final class b2CastResultFcn {

    private b2CastResultFcn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(MemorySegment shapeId, MemorySegment point, MemorySegment normal, float fraction, MemorySegment context);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        Box2D.C_FLOAT,
        b2ShapeId.layout(),
        b2Vec2.layout(),
        b2Vec2.layout(),
        Box2D.C_FLOAT,
        Box2D.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = Box2D.upcallHandle(b2CastResultFcn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(b2CastResultFcn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr, MemorySegment shapeId, MemorySegment point, MemorySegment normal, float fraction, MemorySegment context) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, shapeId, point, normal, fraction, context);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

