// Generated by jextract

package org.box2d.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b2Counters {
 *     int bodyCount;
 *     int shapeCount;
 *     int contactCount;
 *     int jointCount;
 *     int islandCount;
 *     int stackUsed;
 *     int staticTreeHeight;
 *     int treeHeight;
 *     int byteCount;
 *     int taskCount;
 *     int colorCounts[12];
 * }
 * }
 */
public class b2Counters {

    b2Counters() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Box2D.C_INT.withName("bodyCount"),
        Box2D.C_INT.withName("shapeCount"),
        Box2D.C_INT.withName("contactCount"),
        Box2D.C_INT.withName("jointCount"),
        Box2D.C_INT.withName("islandCount"),
        Box2D.C_INT.withName("stackUsed"),
        Box2D.C_INT.withName("staticTreeHeight"),
        Box2D.C_INT.withName("treeHeight"),
        Box2D.C_INT.withName("byteCount"),
        Box2D.C_INT.withName("taskCount"),
        MemoryLayout.sequenceLayout(12, Box2D.C_INT).withName("colorCounts")
    ).withName("b2Counters");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt bodyCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bodyCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static final OfInt bodyCount$layout() {
        return bodyCount$LAYOUT;
    }

    private static final long bodyCount$OFFSET = $LAYOUT.byteOffset(groupElement("bodyCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static final long bodyCount$offset() {
        return bodyCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static int bodyCount(MemorySegment struct) {
        return struct.get(bodyCount$LAYOUT, bodyCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int bodyCount
     * }
     */
    public static void bodyCount(MemorySegment struct, int fieldValue) {
        struct.set(bodyCount$LAYOUT, bodyCount$OFFSET, fieldValue);
    }

    private static final OfInt shapeCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("shapeCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static final OfInt shapeCount$layout() {
        return shapeCount$LAYOUT;
    }

    private static final long shapeCount$OFFSET = $LAYOUT.byteOffset(groupElement("shapeCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static final long shapeCount$offset() {
        return shapeCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static int shapeCount(MemorySegment struct) {
        return struct.get(shapeCount$LAYOUT, shapeCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int shapeCount
     * }
     */
    public static void shapeCount(MemorySegment struct, int fieldValue) {
        struct.set(shapeCount$LAYOUT, shapeCount$OFFSET, fieldValue);
    }

    private static final OfInt contactCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("contactCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final OfInt contactCount$layout() {
        return contactCount$LAYOUT;
    }

    private static final long contactCount$OFFSET = $LAYOUT.byteOffset(groupElement("contactCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static final long contactCount$offset() {
        return contactCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static int contactCount(MemorySegment struct) {
        return struct.get(contactCount$LAYOUT, contactCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int contactCount
     * }
     */
    public static void contactCount(MemorySegment struct, int fieldValue) {
        struct.set(contactCount$LAYOUT, contactCount$OFFSET, fieldValue);
    }

    private static final OfInt jointCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("jointCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static final OfInt jointCount$layout() {
        return jointCount$LAYOUT;
    }

    private static final long jointCount$OFFSET = $LAYOUT.byteOffset(groupElement("jointCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static final long jointCount$offset() {
        return jointCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static int jointCount(MemorySegment struct) {
        return struct.get(jointCount$LAYOUT, jointCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int jointCount
     * }
     */
    public static void jointCount(MemorySegment struct, int fieldValue) {
        struct.set(jointCount$LAYOUT, jointCount$OFFSET, fieldValue);
    }

    private static final OfInt islandCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("islandCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static final OfInt islandCount$layout() {
        return islandCount$LAYOUT;
    }

    private static final long islandCount$OFFSET = $LAYOUT.byteOffset(groupElement("islandCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static final long islandCount$offset() {
        return islandCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static int islandCount(MemorySegment struct) {
        return struct.get(islandCount$LAYOUT, islandCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int islandCount
     * }
     */
    public static void islandCount(MemorySegment struct, int fieldValue) {
        struct.set(islandCount$LAYOUT, islandCount$OFFSET, fieldValue);
    }

    private static final OfInt stackUsed$LAYOUT = (OfInt)$LAYOUT.select(groupElement("stackUsed"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static final OfInt stackUsed$layout() {
        return stackUsed$LAYOUT;
    }

    private static final long stackUsed$OFFSET = $LAYOUT.byteOffset(groupElement("stackUsed"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static final long stackUsed$offset() {
        return stackUsed$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static int stackUsed(MemorySegment struct) {
        return struct.get(stackUsed$LAYOUT, stackUsed$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int stackUsed
     * }
     */
    public static void stackUsed(MemorySegment struct, int fieldValue) {
        struct.set(stackUsed$LAYOUT, stackUsed$OFFSET, fieldValue);
    }

    private static final OfInt staticTreeHeight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("staticTreeHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static final OfInt staticTreeHeight$layout() {
        return staticTreeHeight$LAYOUT;
    }

    private static final long staticTreeHeight$OFFSET = $LAYOUT.byteOffset(groupElement("staticTreeHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static final long staticTreeHeight$offset() {
        return staticTreeHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static int staticTreeHeight(MemorySegment struct) {
        return struct.get(staticTreeHeight$LAYOUT, staticTreeHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int staticTreeHeight
     * }
     */
    public static void staticTreeHeight(MemorySegment struct, int fieldValue) {
        struct.set(staticTreeHeight$LAYOUT, staticTreeHeight$OFFSET, fieldValue);
    }

    private static final OfInt treeHeight$LAYOUT = (OfInt)$LAYOUT.select(groupElement("treeHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static final OfInt treeHeight$layout() {
        return treeHeight$LAYOUT;
    }

    private static final long treeHeight$OFFSET = $LAYOUT.byteOffset(groupElement("treeHeight"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static final long treeHeight$offset() {
        return treeHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static int treeHeight(MemorySegment struct) {
        return struct.get(treeHeight$LAYOUT, treeHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int treeHeight
     * }
     */
    public static void treeHeight(MemorySegment struct, int fieldValue) {
        struct.set(treeHeight$LAYOUT, treeHeight$OFFSET, fieldValue);
    }

    private static final OfInt byteCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("byteCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final OfInt byteCount$layout() {
        return byteCount$LAYOUT;
    }

    private static final long byteCount$OFFSET = $LAYOUT.byteOffset(groupElement("byteCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static final long byteCount$offset() {
        return byteCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static int byteCount(MemorySegment struct) {
        return struct.get(byteCount$LAYOUT, byteCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int byteCount
     * }
     */
    public static void byteCount(MemorySegment struct, int fieldValue) {
        struct.set(byteCount$LAYOUT, byteCount$OFFSET, fieldValue);
    }

    private static final OfInt taskCount$LAYOUT = (OfInt)$LAYOUT.select(groupElement("taskCount"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static final OfInt taskCount$layout() {
        return taskCount$LAYOUT;
    }

    private static final long taskCount$OFFSET = $LAYOUT.byteOffset(groupElement("taskCount"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static final long taskCount$offset() {
        return taskCount$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static int taskCount(MemorySegment struct) {
        return struct.get(taskCount$LAYOUT, taskCount$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int taskCount
     * }
     */
    public static void taskCount(MemorySegment struct, int fieldValue) {
        struct.set(taskCount$LAYOUT, taskCount$OFFSET, fieldValue);
    }

    private static final SequenceLayout colorCounts$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("colorCounts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static final SequenceLayout colorCounts$layout() {
        return colorCounts$LAYOUT;
    }

    private static final long colorCounts$OFFSET = $LAYOUT.byteOffset(groupElement("colorCounts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static final long colorCounts$offset() {
        return colorCounts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static MemorySegment colorCounts(MemorySegment struct) {
        return struct.asSlice(colorCounts$OFFSET, colorCounts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static void colorCounts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, colorCounts$OFFSET, colorCounts$LAYOUT.byteSize());
    }

    private static long[] colorCounts$DIMS = { 12 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static long[] colorCounts$dimensions() {
        return colorCounts$DIMS;
    }
    private static final VarHandle colorCounts$ELEM_HANDLE = colorCounts$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static int colorCounts(MemorySegment struct, long index0) {
        return (int)colorCounts$ELEM_HANDLE.get(struct, colorCounts$OFFSET, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * int colorCounts[12]
     * }
     */
    public static void colorCounts(MemorySegment struct, long index0, int fieldValue) {
        colorCounts$ELEM_HANDLE.set(struct, colorCounts$OFFSET, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

