// Generated by jextract

package org.box2d.internal;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b2DistanceInput {
 *     b2ShapeProxy proxyA;
 *     b2ShapeProxy proxyB;
 *     b2Transform transformA;
 *     b2Transform transformB;
 *     _Bool useRadii;
 * }
 * }
 */
public class b2DistanceInput {

    b2DistanceInput() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b2ShapeProxy.layout().withName("proxyA"),
        b2ShapeProxy.layout().withName("proxyB"),
        b2Transform.layout().withName("transformA"),
        b2Transform.layout().withName("transformB"),
        Box2D.C_BOOL.withName("useRadii"),
        MemoryLayout.paddingLayout(3)
    ).withName("b2DistanceInput");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout proxyA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyA
     * }
     */
    public static final GroupLayout proxyA$layout() {
        return proxyA$LAYOUT;
    }

    private static final long proxyA$OFFSET = $LAYOUT.byteOffset(groupElement("proxyA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyA
     * }
     */
    public static final long proxyA$offset() {
        return proxyA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyA
     * }
     */
    public static MemorySegment proxyA(MemorySegment struct) {
        return struct.asSlice(proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyA
     * }
     */
    public static void proxyA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyA$OFFSET, proxyA$LAYOUT.byteSize());
    }

    private static final GroupLayout proxyB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("proxyB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyB
     * }
     */
    public static final GroupLayout proxyB$layout() {
        return proxyB$LAYOUT;
    }

    private static final long proxyB$OFFSET = $LAYOUT.byteOffset(groupElement("proxyB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyB
     * }
     */
    public static final long proxyB$offset() {
        return proxyB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyB
     * }
     */
    public static MemorySegment proxyB(MemorySegment struct) {
        return struct.asSlice(proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2ShapeProxy proxyB
     * }
     */
    public static void proxyB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, proxyB$OFFSET, proxyB$LAYOUT.byteSize());
    }

    private static final GroupLayout transformA$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transformA"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2Transform transformA
     * }
     */
    public static final GroupLayout transformA$layout() {
        return transformA$LAYOUT;
    }

    private static final long transformA$OFFSET = $LAYOUT.byteOffset(groupElement("transformA"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2Transform transformA
     * }
     */
    public static final long transformA$offset() {
        return transformA$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2Transform transformA
     * }
     */
    public static MemorySegment transformA(MemorySegment struct) {
        return struct.asSlice(transformA$OFFSET, transformA$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2Transform transformA
     * }
     */
    public static void transformA(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transformA$OFFSET, transformA$LAYOUT.byteSize());
    }

    private static final GroupLayout transformB$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("transformB"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2Transform transformB
     * }
     */
    public static final GroupLayout transformB$layout() {
        return transformB$LAYOUT;
    }

    private static final long transformB$OFFSET = $LAYOUT.byteOffset(groupElement("transformB"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2Transform transformB
     * }
     */
    public static final long transformB$offset() {
        return transformB$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2Transform transformB
     * }
     */
    public static MemorySegment transformB(MemorySegment struct) {
        return struct.asSlice(transformB$OFFSET, transformB$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2Transform transformB
     * }
     */
    public static void transformB(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, transformB$OFFSET, transformB$LAYOUT.byteSize());
    }

    private static final OfBoolean useRadii$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("useRadii"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static final OfBoolean useRadii$layout() {
        return useRadii$LAYOUT;
    }

    private static final long useRadii$OFFSET = $LAYOUT.byteOffset(groupElement("useRadii"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static final long useRadii$offset() {
        return useRadii$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static boolean useRadii(MemorySegment struct) {
        return struct.get(useRadii$LAYOUT, useRadii$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool useRadii
     * }
     */
    public static void useRadii(MemorySegment struct, boolean fieldValue) {
        struct.set(useRadii$LAYOUT, useRadii$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

