// Generated by jextract

package org.box2d.internal;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct b2RayResult {
 *     b2ShapeId shapeId;
 *     b2Vec2 point;
 *     b2Vec2 normal;
 *     float fraction;
 *     int nodeVisits;
 *     int leafVisits;
 *     _Bool hit;
 * }
 * }
 */
public class b2RayResult {

    b2RayResult() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        b2ShapeId.layout().withName("shapeId"),
        b2Vec2.layout().withName("point"),
        b2Vec2.layout().withName("normal"),
        Box2D.C_FLOAT.withName("fraction"),
        Box2D.C_INT.withName("nodeVisits"),
        Box2D.C_INT.withName("leafVisits"),
        Box2D.C_BOOL.withName("hit"),
        MemoryLayout.paddingLayout(3)
    ).withName("b2RayResult");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout shapeId$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("shapeId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2ShapeId shapeId
     * }
     */
    public static final GroupLayout shapeId$layout() {
        return shapeId$LAYOUT;
    }

    private static final long shapeId$OFFSET = $LAYOUT.byteOffset(groupElement("shapeId"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2ShapeId shapeId
     * }
     */
    public static final long shapeId$offset() {
        return shapeId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2ShapeId shapeId
     * }
     */
    public static MemorySegment shapeId(MemorySegment struct) {
        return struct.asSlice(shapeId$OFFSET, shapeId$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2ShapeId shapeId
     * }
     */
    public static void shapeId(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shapeId$OFFSET, shapeId$LAYOUT.byteSize());
    }

    private static final GroupLayout point$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("point"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2Vec2 point
     * }
     */
    public static final GroupLayout point$layout() {
        return point$LAYOUT;
    }

    private static final long point$OFFSET = $LAYOUT.byteOffset(groupElement("point"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2Vec2 point
     * }
     */
    public static final long point$offset() {
        return point$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2Vec2 point
     * }
     */
    public static MemorySegment point(MemorySegment struct) {
        return struct.asSlice(point$OFFSET, point$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2Vec2 point
     * }
     */
    public static void point(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, point$OFFSET, point$LAYOUT.byteSize());
    }

    private static final GroupLayout normal$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("normal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * b2Vec2 normal
     * }
     */
    public static final GroupLayout normal$layout() {
        return normal$LAYOUT;
    }

    private static final long normal$OFFSET = $LAYOUT.byteOffset(groupElement("normal"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * b2Vec2 normal
     * }
     */
    public static final long normal$offset() {
        return normal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * b2Vec2 normal
     * }
     */
    public static MemorySegment normal(MemorySegment struct) {
        return struct.asSlice(normal$OFFSET, normal$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * b2Vec2 normal
     * }
     */
    public static void normal(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, normal$OFFSET, normal$LAYOUT.byteSize());
    }

    private static final OfFloat fraction$LAYOUT = (OfFloat)$LAYOUT.select(groupElement("fraction"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float fraction
     * }
     */
    public static final OfFloat fraction$layout() {
        return fraction$LAYOUT;
    }

    private static final long fraction$OFFSET = $LAYOUT.byteOffset(groupElement("fraction"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float fraction
     * }
     */
    public static final long fraction$offset() {
        return fraction$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float fraction
     * }
     */
    public static float fraction(MemorySegment struct) {
        return struct.get(fraction$LAYOUT, fraction$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float fraction
     * }
     */
    public static void fraction(MemorySegment struct, float fieldValue) {
        struct.set(fraction$LAYOUT, fraction$OFFSET, fieldValue);
    }

    private static final OfInt nodeVisits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nodeVisits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nodeVisits
     * }
     */
    public static final OfInt nodeVisits$layout() {
        return nodeVisits$LAYOUT;
    }

    private static final long nodeVisits$OFFSET = $LAYOUT.byteOffset(groupElement("nodeVisits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nodeVisits
     * }
     */
    public static final long nodeVisits$offset() {
        return nodeVisits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nodeVisits
     * }
     */
    public static int nodeVisits(MemorySegment struct) {
        return struct.get(nodeVisits$LAYOUT, nodeVisits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nodeVisits
     * }
     */
    public static void nodeVisits(MemorySegment struct, int fieldValue) {
        struct.set(nodeVisits$LAYOUT, nodeVisits$OFFSET, fieldValue);
    }

    private static final OfInt leafVisits$LAYOUT = (OfInt)$LAYOUT.select(groupElement("leafVisits"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int leafVisits
     * }
     */
    public static final OfInt leafVisits$layout() {
        return leafVisits$LAYOUT;
    }

    private static final long leafVisits$OFFSET = $LAYOUT.byteOffset(groupElement("leafVisits"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int leafVisits
     * }
     */
    public static final long leafVisits$offset() {
        return leafVisits$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int leafVisits
     * }
     */
    public static int leafVisits(MemorySegment struct) {
        return struct.get(leafVisits$LAYOUT, leafVisits$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int leafVisits
     * }
     */
    public static void leafVisits(MemorySegment struct, int fieldValue) {
        struct.set(leafVisits$LAYOUT, leafVisits$OFFSET, fieldValue);
    }

    private static final OfBoolean hit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("hit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool hit
     * }
     */
    public static final OfBoolean hit$layout() {
        return hit$LAYOUT;
    }

    private static final long hit$OFFSET = $LAYOUT.byteOffset(groupElement("hit"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool hit
     * }
     */
    public static final long hit$offset() {
        return hit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool hit
     * }
     */
    public static boolean hit(MemorySegment struct) {
        return struct.get(hit$LAYOUT, hit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool hit
     * }
     */
    public static void hit(MemorySegment struct, boolean fieldValue) {
        struct.set(hit$LAYOUT, hit$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

